### ISSUE TITLE
Proot is crashing in latest alpine

### ISSUE THREAD

**Issue by Hax4us** [termux/proot#102]
Here is log file with proot_verbose=9  https://github.com/Hax4us/Hax4us.github.io/blob/master/files/typescript
And this is happening only while installing java and more specifically, while executing `java-common-0.2-r0.trigger` 
Here is screenshot
![Screenshot_2020-04-20-17-53-02-624_com termux](https://user-images.githubusercontent.com/30441647/79751186-ccbf1d80-832f-11ea-8457-5e282a7b66e4.jpg)
And more noticeable thing is that it's only happening in latest build of alpine i.e 3.11.5
I didn't face this issue in alpine 3.10.2

**Comment by oxr463** [comment]
Is this unique to PRoot? Are you sure it is not an OpenJDK issue in Alpine?

**Comment by Hax4us** [comment]
I am not sure that's why i opened issue

**Comment by xeffyr** [comment]
> i can confirm that there is no issue in openjdk of alpine but issue in rootfs , because i just installed openjdk from latest alpine in old version of alpine

Happens with latest rootfs & upgraded packages as well.

```
localhost:/# apk add openjdk11
(1/29) Installing openjdk11-jmods (11.0.5_p10-r0)
(2/29) Installing openjdk11-doc (11.0.5_p10-r0)
(3/29) Installing java-common (0.2-r0)
(4/29) Installing libffi (3.2.1-r6)
(5/29) Installing p11-kit (0.23.18.1-r0)
(6/29) Installing libtasn1 (4.15.0-r0)
(7/29) Installing p11-kit-trust (0.23.18.1-r0)
(8/29) Installing ca-certificates (20191127-r1)
(9/29) Installing java-cacerts (1.0-r0)
(10/29) Installing openjdk11-jre-headless (11.0.5_p10-r0)
(11/29) Installing libxau (1.0.9-r0)
(12/29) Installing libbsd (0.10.0-r0)
(13/29) Installing libxdmcp (1.1.3-r0)
(14/29) Installing libxcb (1.13.1-r0)
(15/29) Installing libx11 (1.6.9-r0)
(16/29) Installing libxext (1.3.4-r0)
(17/29) Installing libxi (1.7.10-r0)
(18/29) Installing libxrender (0.9.10-r3)
(19/29) Installing libxtst (1.2.3-r3)
(20/29) Installing alsa-lib (1.2.1.2-r0)
(21/29) Installing libbz2 (1.0.8-r1)
(22/29) Installing libpng (1.6.37-r1)
(23/29) Installing freetype (2.10.1-r0)
(24/29) Installing giflib (5.2.1-r0)
(25/29) Installing libjpeg-turbo (2.0.4-r0)
(26/29) Installing lcms2 (2.9-r1)
(27/29) Installing openjdk11-jre (11.0.5_p10-r0)
(28/29) Installing openjdk11-jdk (11.0.5_p10-r0)
(29/29) Installing openjdk11 (11.0.5_p10-r0)
Executing busybox-1.31.1-r9.trigger
Executing java-common-0.2-r0.trigger
proot warning: signal 11 received from process 24
```

**Comment by michalbednarski** [comment]
I'm looking into this, so far I've got following bug reproducer:

```
echo 'v=`true something*`' > trigger.sh
busybox sh trigger.sh
```
