### ISSUE TITLE
Does proot under termux support android-shmem?

### ISSUE THREAD

**Issue by Root-voidX** [termux/proot#103]
Hello devs, users and friends,

I am running Ubuntu via Proot on Termux (installed with AnLinux). I understand that android doesn't support shared memory access, which gives segfaults to many applications for me. I heard about android-shmem, does termux proot have android-shmem?

**Comment by ZhymabekRoman** [comment]
Hello, @Root-voidX !
Now proot supports shm, you can use now.

**Comment by SDRausty** [comment]
@Root-voidX this appears to be integrated.  Do you agree?
