### ISSUE TITLE
flatpak remote-add rust_nightly https://haeckerfelix.de/~repo/rust_nightly.flatpakrepo issue

### ISSUE THREAD

**Issue by JanuszChmiel** [termux/proot#106]
This command is causing error when running as root. Unauthorized access to memory (SIGSEGV)
And when I run it as non root user

Error, can not connect to The system bus.
It is so sad, that there are still apps which strictly depend on communication with Dbus system sockets. And as A result, those apps will never run with Termux and Proot on non rooted devices. And running Qemu with full Linux distro is so slow without special patched Android kernel which contain Kqemu acceleration module. Sad story.

**Comment by Grimler91** [comment]
Closing since this has not been updated in quite a while, please fill in the [bug report template](https://github.com/termux/proot/issues/new?assignees=&labels=&template=bug_report.md) if this is still an issue
