### ISSUE TITLE
why flatpak remote-add https://flathub.org/repo/flathub.flatpakrepo causes memory error on Arch Linux

### ISSUE THREAD

**Issue by JanuszChmiel** [termux/proot#110]
Why do you think, that The following command causes memory issues when run as root?

flatpak remote-add https://flathub.org/repo/flathub.flatpakrepo
There is memory crash unauthorized access to memory.
And when I have tried to run it by typing
dbus-run-session flatpak remote-add https://flathub.org/repo/flathub.flatpakrepo
There was error that FD limit can not be set to 65536.

But. Even if we could solve this problem. Flatpak uses very probably memory calls which are incompatible with Proot because it run process in A isoloated santbox.

**Comment by Grimler91** [comment]
Closing since this has not been updated in quite a while, please fill in the [bug report template](https://github.com/termux/proot/issues/new?assignees=&labels=&template=bug_report.md) if this is still an issue
