### ISSUE TITLE
Libre Office can not be used on Android 8 and newer /proc folder can not be accessssssedPlease if I install LIbre office tTo ArchLinux AArch64 Libreoffice can not be started because /proc folder can not be accessssed. I Am ussssiing ArchLinux installation script by Mr Rausty. Marco window manager work thanks to used work around reeeelated to /proc access. But LIbreoffice binary do not work.

### ISSUE THREAD

**Issue by JanuszChmiel** [termux/proot#112]

**Comment by JanuszChmiel** [comment]
I Am using ArchLinux AAArch64 which I have installed bbbby using install script from MR Rausty. Used work around related to /proc folder
 not help. Because when I have installed Libre office /proc folder can not be accessssed, so Libreoffice can not be loaded to RAM and do not work.
Do you think if there is some other possibility how to force Libreoffice tooo work?
Why Libreoffice binary must access /proc, does it monitor Java sub processes of    its components?
Thank you very much for any advice which would help.
May be, that Proot could intercept if Libreoffice binary try to   open /proc folder. And in this case some new code would be started in Proot.

**Comment by radumamy** [comment]
See if this script can help. Thanks.

https://raw.githubusercontent.com/ivosz/AndronixOrigin/master/Uninstall/librepatch_arch.sh

**Comment by JanuszChmiel** [comment]
Oh thank you very much, I will try yours script. It would be excellent, if
Libreoffice could be used, because Google Play version will never support so
much hod keys like a desktop version. Thank you very much for yours time and
for yours thinkink

**Comment by JanuszChmiel** [comment]
Yours path have solved my issue. Libreoffice can be launched without
problems like on ANdroid 7 and older. Very well done.
It is my fortune, that it had not been necessary to modify Libreoffice
binary module source code or even Proot source.
Excellent job. YOu can close this issue.

**Comment by JanuszChmiel** [comment]
Do you think about reliable VNC client for Android app which support
hardware keyboard by The most reliable way? I have found out, that this
problem is The most tricky. Because every Android version handle keyboard
differently, AOSP Android module behaves differently on every Android
version As A result, some keys are not detected on some Android VNC clients.
Such as Capslock, Shift or ALT.

**Comment by radumamy** [comment]
> Yours path have solved my issue. Libreoffice can be launched without problems like on ANdroid 7 and older. Very well done. It is my fortune, that it had not been necessary to modify Libreoffice binary module source code or even Proot source. Excellent job. YOu can close this issue.

You're welcome. It is not my script so I cannot take credit for it, it is something I stumbled upon. I cannot close the issue, you can do this yourself or wait for an admin to do it. Thanks.

**Comment by radumamy** [comment]
> Do you think about reliable VNC client for Android app which support hardware keyboard by The most reliable way? I have found out, that this problem is The most tricky. Because every Android version handle keyboard differently, AOSP Android module behaves differently on every Android version As A result, some keys are not detected on some Android VNC clients. Such as Capslock, Shift or ALT.

RealVNC Viewer works fine for me. Thanks.
https://play.google.com/store/apps/details?id=com.realvnc.viewer.android

**Comment by JanuszChmiel** [comment]
But Real VNC do not allow Me to set IP address and other settings befor I
will not create account. I hope, that it will work for free when I will
setup account.

**Comment by xeffyr** [comment]
> But Real VNC do not allow Me to set IP address and other settings

I don't know what you are talking about but RealVNC viewer is a **free** application and allows to create connections without RealVNC account.

Here is a Termux script for automating VNC connection, if you can't add a new one to address book by pressing button "+":
```
termux-open "vnc://127.0.0.1:5901"
```

**Comment by JanuszChmiel** [comment]
Screen reader inform Me about address book item and when I click on it I do
not hear some change. And there is signup button, settings button.
Maz be, that GUI is not fully accessible. Can I simply past The code on
Termux window to ry it out?
I will try it and thank you for yours support.

**Comment by JanuszChmiel** [comment]
Thank you Mr Pliush. I can connect thanks to yours script. Very well done.
Thank you again.

**Comment by radumamy** [comment]
> Screen reader inform Me about address book item and when I click on it I do not hear some change. And there is signup button, settings button. Maz be, that GUI is not fully accessible. Can I simply past The code on Termux window to ry it out? I will try it and thank you for yours support.

Don't you have the plus button? 
![Screenshot_20200529-120122](https://user-images.githubusercontent.com/63680669/83253471-ee1fee80-a1a4-11ea-849f-eb6c9fbd932a.png)

**Comment by JanuszChmiel** [comment]
Oh my painfull life. I have connected successfully to VNC server but
unfortunately for Me, Real VNC company do not automatically allow Me to use
bluetooth hardware keyboard. There are many buttons on The screen. And even
Orca screen reader detect, that there is no feetback by using XKB protocol
from some app so it crashes. I will be hoping, that some of graphical
buttons will enable hardware keyboard support.
Other VNC clients have enabled keyboard by default including Mocha VNC, but
those clients lack some key support such as Numeric insert or Capslock or
Shift keys.
Very strange.

**Comment by JanuszChmiel** [comment]
I have found graphical button, but Capslock key is not autodetected. So it
is really some Android AOSP module bug if also so professionally developed
app from big company have The problem with this key detection.
