### ISSUE TITLE
proot warning: can't set tracee registers in workaround: No such process

### ISSUE THREAD

**Issue by JanuszChmiel** [termux/proot#114]
What does it mean please? Ir Proot is being forced to display this warning? Is it because work around related to /proc folder access for Android 8 and newer is making troubles? Or is it because there are some memory allocation problems when some window have been closed? I have got this error after pressin CTRL+w when i have closed Lx music simple music player for Lxde. May be, that CTRL+w is not assigned to close The window. I can not use ALT+F4 thanks to my BLuetooth keyboard, which do not contain Function keys.

**Comment by Grimler91** [comment]
Closing since this has not been updated in quite a while, please fill in the [bug report template](https://github.com/termux/proot/issues/new?assignees=&labels=&template=bug_report.md) if this is still an issue
