### ISSUE TITLE
Turmex prior Error 

### ISSUE THREAD

**Issue by garypppp** [termux/proot#115]
Proot error: '/usr/bin/fish' not found (root = /data/data/com.termux/files, cwd = /data/data/com.termux/files/home/termux-ubuntu, $PATH=(null))
fatal error: see `proot --help`.

Ubuntu

Android 8.0.0

How do I fix this

**Comment by xeffyr** [comment]
Replace `/usr/bin/fish` with `/bin/bash` in your startup script.

**Comment by garypppp** [comment]
How and why
