### ISSUE TITLE
Please Update to 5.2.0

### ISSUE THREAD

**Issue by Flytreels** [termux/proot#118]
Please.

**Comment by Grimler91** [comment]
Proot 5.2.0 has not been released, only an alpha version. Is there a specific patch you want backported?

**Comment by xeffyr** [comment]
I have checked its changelog and it looks like same as our current version. Termux proot is a fork of original and has own roadmap.

**Comment by Flytreels** [comment]
I want to make a patch version for Termux, but the compiled version cannot be used.
Can you tell me how to add the patch, thank you!

**Comment by xeffyr** [comment]
@Flytreels First of all, decide **what you want to backport here**, before attempting to patch anything here. Is there any specific reason why you want 5.2.0 proot ? Our version has everything that official proot has, probably even more, so I'm curious regarding what you need. Just version number?

**Comment by Flytreels** [comment]
I want to use new features and some fixes to keep up to date.

**Comment by xeffyr** [comment]
> I want to use new features

This version has **more** features than original.

**Comment by xeffyr** [comment]
If v5.2.0 has some features not available in this repository, list them here.

**Comment by Flytreels** [comment]
Ok
