### ISSUE TITLE
Doom Emacs installing

./path/path.c:547: Comparison compare_paths2(const char *, size_t, const char *, size_t): assertion "length2 > 0"

### ISSUE THREAD

**Issue by artamudo** [termux/proot#123]
How long will it be ignored?

Alpine Linux under Termux.

**Comment by michalbednarski** [comment]
Fixed version is now available in Termux repo

> How long will it be ignored?

I'm pretty sure this phrase is on some 'how not to report issues' guide, but sometimes issues get forgotten ([although searching for compare_paths2 issues in this repo find only this one](https://github.com/termux/proot/issues?q=compare_paths2)), sometimes similar error messages appear for different problems and also I work on proot in my free time.

**Comment by artamudo** [comment]
Tnx.

**Comment by codygman** [comment]
>> How long will it be ignored?
> I'm pretty sure this phrase is on some 'how not to report issues' guide

It sure should be if not.


> but sometimes issues get forgotten (although searching for compare_paths2 issues in this repo find only this one), sometimes similar error messages appear for different problems and also I work on proot in my free time.

You are fine and your response(s) are totally reasonable. Though I know it's hard to ignore statements like that.

Thanks for your fine work :smile:
