### ISSUE TITLE
mkfifo -m error

### ISSUE THREAD

**Issue by SDRausty** [termux/proot#126]
The command `mkfifo -m o+w /tmp/tmp_random ` fails in PRoot with the this error: `mkfifo: cannot set permissions of '/tmp/tmp_random': Invalid argument`.  The command `mkfifo -m o+w $TMPDIR/tmp_random` works correctly without PRoot.

**Comment by SDRausty** [comment]
@michalbednarski thank you for resolving this matter:
```
mkfifo -m o+w /tmp/tmp_random
ls -al /tmp/tmp_random
prw-rw-rw- 1 root root 0 Oct 28 22:13 /tmp/tmp_random
```
When logged in as a user named user:
```
ls -al /tmp/tmp_random
prw-rw-rw- 1 user user 0 Oct 28 22:13 /tmp/tmp_random
```
This behavior change in ownership behavior causes all sorts of havoc for the user login; do you have any advice regarding this change in ownership derived from PRoot login?  The PRoot init statement for root is:
`exec proot --kernel-release=4.14.117-perf+-generic --kill-on-exit --link2symlink -0 -r /data/data/com.termux/files/home/arch -b /data/data/com.termux/files/home/arch/var/binds/fbindprocpcidevices:/proc/bus/pci/devices -b /data/data/com.termux/files/home/arch/var/binds/fbindprocshmem:/proc/shmem -b /data/data/com.termux/files/home/arch/var/binds/fbindprocversion:/proc/version -b /apex:/apex -b /dev/ashmem:/dev/ashmem -b /storage/:/storage/ -b /data/data/com.termux/files/home:/data/data/com.termux/files/home -b /dev/urandom:/dev/random -b /data/data/com.termux/files/usr:/data/data/com.termux/files/usr -b /proc/:/proc/ -b /vendor/:/vendor/ -b /proc/self/fd:/dev/fd -b /system/:/system/ -b /data/data/com.termux/files/home/arch/var/binds/fbindprocuptime:/proc/uptime -b /data/data/com.termux/files/home/arch/tmp:/dev/shm -b /data/data/com.termux/files/home/arch/var/binds/fbindprocstat:/proc/stat -b /sys/:/sys/ -b /dev/:/dev/ -w /root /usr/bin/env -i HOME=/root TERM="xterm-256color" TMPDIR=/tmp ANDROID_DATA=/data  /bin/bash -l`

Is there anything in the PRoot init statement that can be done to help resolving the change in ownership that appears to be based on login type?

**Comment by SDRausty** [comment]
I appears that a number of commands that had difficulty functioning now work!  The commands `byobu` and `tmux` now work as expected;  Thank you!

**Comment by michalbednarski** [comment]
File ownership is in normal proot version not associated with files, UserLAnd version does that, however that feature is behind compile time switch (`-D USERLAND`, although I'm usually not testing that version)

**Comment by SDRausty** [comment]
> [root02:07~]$ mkfifo -m o+w /tmp/tmp_random
mkfifo: cannot create fifo '/tmp/tmp_random': Function not implemented`

**Comment by SDRausty** [comment]
https://github.com/termux/proot/issues/140

**Comment by SDRausty** [comment]
The following result is with the [`proot` USERLAND 
compile time option](https://github.com/termux/proot/issues/140#issuecomment-749032651_) built and installed from source code in device:

> [root11:07~]$ mkfifo -m o+w /tmp/tmp_random
mkfifo: cannot create fifo '/tmp/tmp_random': Function not implemented

**Comment by SDRausty** [comment]
This error is resolved; Thank you for fixing it 🎵 🎶
