### ISSUE TITLE
Golang won't work with proot + QEMU (x86)

### ISSUE THREAD

**Issue by ZhymabekRoman** [termux/proot#128]
Hello. Golang won't work. I use qemu-i386-static from the debian repository. The first time run 'go', this is the error: 
`root@localhost:/home# arch
i686
root@localhost:/home# go --version
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault`

When i run 'go' for the second time:

`root@localhost:/home# go --version
fatal: morestack on g0
fatal: morestack on gsignal
panic during panic
SIGTRAP: trace trap
PC=0x80a7362 m=2 sigcode=128

goroutine 0 [idle]:
runtime.abort()
        /usr/local/go/src/runtime/asm_386.s:861SIGTRAP: trace trap +
0x2PC=0x80a7362 m=2 sigcode=128

goroutine 0 [idle]:

runtime.morestack()
        /usr/local/go/src/runtime/asm_386.s:444 +0x39
runtime.abort()
        /usr/local/go/src/runtime/asm_386.s:861 +0x2
runtime.morestack(
)
        /usr/local/go/src/runtime/asm_386.s:goroutine 1 [437running +0x24, locked to thread
]:
        goroutine running on other thread; stack unavailable

goroutine 1 [runningeax    , locked to thread]:
0x1c    goroutine running on other thread; stack unavailable

ebx    0x2

ecx    eax    0x8566fe10x17

ebx    0x2edx
ecx    0x1c0x8563a80

edx    edi    0x17
0x855a10bedi
0x0
esi    esi    0xcbc004600xcbc00540

ebp    ebp    0x00x514ff2a4

esp    esp    0x408007540x514ff2a4

eip    0x80a7362
eflags 0x202eip
0x80a7362
eflags cs     0x202
0x23cs     0x23

fs     fs     0x00x0

gs     gs     0x330x33

root@localhost:/home#`
![Screenshot_20201031-092337_Termux](https://user-images.githubusercontent.com/61125068/97770253-bfdf7a00-1b5b-11eb-9f13-42287bd90dc8.jpg)

What is the problem? In Exagear golang works perfectly

**Comment by xeffyr** [comment]
This is general QEMU issue and happens in Ubuntu as well.

`qemu-user` is limited in emulation features and less stable than qemu-system in overall.

![Снимок экрана от 2020-10-31 10-56-03](https://user-images.githubusercontent.com/25881154/97775248-e4d9ea00-1b67-11eb-9280-c7edbe0b72ce.png)
