### ISSUE TITLE
Problems with apt with Ubuntu 16.04

### ISSUE THREAD

**Issue by WMCB-Tech** [termux/proot#130]
Hey. can someone help me. i setup an Ubuntu 16.04 chroot environment and it seems there's a problem with apt but new versions works fine and idk why:

![Screenshot_2020-11-04-15-32-34-71.jpg](https://user-images.githubusercontent.com/65075766/98082316-812b2600-1eb3-11eb-9ca4-42a60e276f5f.jpg)

I tested both Xenial and Trusty and gives me about apt can't open security status channel

Tested on my Android 9 Device

**Comment by michalbednarski** [comment]
Haven't tested myself but it seems that you should be able to workaround this by `LD_PRELOAD`'ing library with following code
```c
int is_selinux_enabled(void) { return 0; }
```

```sh
gcc sefake.c -o sefake.so -shared
LD_PRELOAD=/root/sefake.so apt update
```

**Comment by WMCB-Tech** [comment]
@michalbednarski it seems there's an compilation error
```
sefake.c:1:66: error: stray ‘\240’ in program
    1 | bled(void) { return��0; }
      |                                      ^

sefake.c:1:67: error: stray ‘\342’ in program
    1 | bled(void) { return ���0; }
      |                                       ^

sefake.c:1:68: error: stray ‘\200’ in program
    1 | bled(void) { return ���0; }
      |                                        ^

sefake.c:1:69: error: stray ‘\213’ in program
    1 | bled(void) { return ��0; }
      |                                         ^

sefake.c:1:71: error: stray ‘\342’ in program
    1 | void) { return 0���; }
      |                                ^

sefake.c:1:72: error: stray ‘\200’ in program
    1 | oid) { return 0���; }
      |                                ^

sefake.c:1:73: error: stray ‘\213’ in program
    1 | id) { return 0��; }
      |                                ^
```

Am i missing something?

**Comment by michalbednarski** [comment]
Looks like some (nonprintable?) characters were added on copy-paste, try retyping sefake.c into new file

**Comment by WMCB-Tech** [comment]
It does work but it seems there's an error:
```
dpkg (subprocess): cannot set security execution context for maintainer script: Permission denied
```

**Comment by ZhymabekRoman** [comment]
> ![Screenshot_2020-11-06-16-58-05-84.jpg](https://user-images.githubusercontent.com/65075766/98346682-46f78b00-2051-11eb-879c-4054346780ed.jpg)
> 
Try add -L flag when starting proot

**Comment by ZhymabekRoman** [comment]
> ```
> dpkg (subprocess): cannot set security execution context for maintainer script: Permission denied
> ```

Try use my LD_PRELOAD libraries :

[Dvget.zip](https://github.com/termux/proot/files/5551804/Dvget.zip)

**Comment by WMCB-Tech** [comment]
Does that work with arm64?
