### ISSUE TITLE
Distro doesn't work on Amazon FireTV 2nd generation

### ISSUE THREAD

**Issue by radumamy** [termux/proot#131]
Hi,

I am having difficulties getting openSUSE distro to work on Amazon FireTV 2nd generation (box not stick). The device is aarch64 running Android 5.1.1, Kernel 3.10.61, Termux 0.75 and proot 5.1.0. I understand that this is a legacy environment and is not getting any more updates, so I apologise in advance for asking some questions.

It seems like I don't have Internet connectivity from inside the distro, e.g. Ping hangs (cannot ping localhost either), cannot install Packages zypper hangs, etc. The same installation script works fine on my phone.  

`https://raw.githubusercontent.com/radumamy/Termux-openSUSE/master/Scripts/Installer/openSUSE/Tumbleweed/opensuse-tumbleweed-jeos.sh`

Has anyone tried distros on FireTV before? 

Is there anything I can do to diagnose this issue?

Kind Regards, 
Radu

**Comment by xeffyr** [comment]
> The device is aarch64 running Android 5.1.1

Android 5.1 is out of support.

**Comment by radumamy** [comment]
@michalbednarski Could I please have some guidance? I apologise for tagging you in, you have kindly helped me previously. I am not asking for development fixes, just some guidance. I have been trying desperately for past few days now to get this fixed, but I am  stuck. I have installed Alpine and that has Internet connectivity inside proot, e.g. Package manager works, but I cannot get openSUSE Zypper to run. I have populated `/etc/hosts` and /etc/resolv.conf` with the same details from Alpine and it still doesn't work. What am I missing? Thank you in advance.

**Comment by xeffyr** [comment]
@radumamy First check whether networking works at all under proot. For example by using this command:
```
proot curl https://google.com
```
This one normally should give some html output.

**Comment by xeffyr** [comment]
If `proot curl` worked, then I suggest to try different name servers for /etc/resolv.conf. Try out these:
1. `nameserver 1.1.1.1`
2. `nameserver 8.8.8.8`
3. `nameserver 208.67.222.222`
4. `nameserver 172.104.136.243`

Don't put all at once.

**Comment by radumamy** [comment]
Thank you @xeffyr. `proot curl` in Termux seems to be working as I am getting a html response `The document has moved` but not inside the distro. I have tried all the suggested nameservers, one at a time and nothing. `curl` just hangs. 😕

**Comment by michalbednarski** [comment]
You might want to try `nscd.py` script from https://github.com/termux/proot/issues/101#issuecomment-599036821
(In that issue it was established that non-DNS traffic worked on device, don't know if Fire TV is similar in this regard nor whenever problem is caused by seccomp/selinux/something else)

**Comment by radumamy** [comment]
![Screenshot_20201111-120954~2](https://user-images.githubusercontent.com/63680669/98810550-54c55b80-2417-11eb-95af-2745d221b0f1.png)
@michalbednarski Thank you. How long does this script normally takes to run?

**Comment by xeffyr** [comment]
It will run infinitely because that's a server.

**Comment by radumamy** [comment]
![Screenshot_20201111-132050~2](https://user-images.githubusercontent.com/63680669/98816954-53009580-2421-11eb-8431-03be3df3448f.png)
Thanks @xeffyr.
I have relaunched Termux, set off the script, started a new Termux session, launched the distro and tried `curl`. Unfortunately it's exactly the same result. 😕

**Comment by xeffyr** [comment]
@radumamy Is `ncsd.py` still running when you starting proot shell or not?

**Comment by radumamy** [comment]
![Screenshot_20201111-140159~2](https://user-images.githubusercontent.com/63680669/98820912-be993180-2426-11eb-8347-5934a84155b4.png)
@xeffyr Yes, it is. 😕

**Comment by radumamy** [comment]
![Screenshot_20201113-102813~2](https://user-images.githubusercontent.com/63680669/99062781-68013400-259b-11eb-886c-5d3d0d0af703.png)
Good Morning gents. If I'm stopping the script using Ctrl + C, I'm getting the attached. Is this the expected behaviour? Is there anything else I can try? If I root my device, will it make a difference? I've got 2 boxes and it's a shame I can't put them to good use. Thank you.

**Comment by radumamy** [comment]
Good Afternoon @michalbednarski @xeffyr
It appears I do have Internet connection from inside of distro as I've managed to install Plex Media Server on it and I can access this server when I'm out and about. It looks like higher port numbers have Internet access.

I've added `proot - p` to the launch script and when I try `curl` again it does say connected to Google on 443, but still doesn't receives the reply.

I feel I'm really close to getting this resolved, is there anything you guys might think could help fix this issue for me?

Thank you.

**Comment by ilmanowar** [comment]
As mentioned by michalbednarski, the problem could be related to the #101 (comment).
I believe so because I have Amazon Tablet Fire. And it does not allow an internet connection for the Linux distro. 
Googling I come out to the #101 issue and this one.
Then I guessed that a VPN app (PIA) could re-route the traffic for me. It worked.
So the simple way for you could be installing a VPN app.
