### ISSUE TITLE
Issues with Synaptic

### ISSUE THREAD

**Issue by WMCB-Tech** [termux/proot#135]
Hello, can someone help me, so i was about to run synaptic on debian proot but i got this issue:
![126930871_803144773799752_6251995648774799482_n](https://user-images.githubusercontent.com/65075766/100319478-a1ee2380-2ffa-11eb-9cd9-32f4d89aab4c.jpg)

I was searching to the internet about this problem but i had no luck but when i found out that when i use other debian rootfs. synaptic works

idk if it's proot-related or not (Haven't tested this rootfs on my PC to chroot it and test synaptic)

btw, this is running as root

Rootfs has synaptic problems:
https://github.com/debuerreotype/docker-debian-artifacts/tree/dist-arm64v8

Rootfs which synaptic works:
https://uk.images.linuxcontainers.org/images/debian/

Idk if there's a lack of dependencies or so on

**Comment by michalbednarski** [comment]
Looks like this is due to `Dir::Cache::pkgcache "";` defined in `/etc/apt/apt.conf.d/docker-clean` of that rootfs.

**Comment by WMCB-Tech** [comment]
It seems userland occurs the same, [issue no 916](https://github.com/CypherpunkArmory/UserLAnd/issues/916)

**Comment by WMCB-Tech** [comment]
And deleting it works, thanks for the response

**Comment by michalbednarski** [comment]
Yes, looks like UserLAnd Debian has same configuration (in same file), pinging @corbinlc

**Comment by WMCB-Tech** [comment]
Yep, Ubuntu has docker configuration as well that may interfere synaptic:
![Screenshot_2020-11-28-21-29-27-82.jpg](https://user-images.githubusercontent.com/65075766/100516769-04911c00-31c1-11eb-90c0-38c053054817.jpg)
