### ISSUE TITLE
-b option enable for access mounted ext4?

### ISSUE THREAD

**Issue by gyurmogyuri** [termux/proot#136]
Hello I would like to know how to access a library?  I know -b does that.  But on proot command, I don't get what I want.  Can anyone help?

```
$  proot-distro login ubuntu-20.04
root@localhost:~# echo "$SHELL"
/bin/bash
```

```
$ proot -R /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu-20.04 -0 -w / -b /dev -b /proc -b /sys  -b /mnt/media_rw/sdcard1 /bin/bash --login
bash: groups: command not found
root@localhost:/# echo "$SHELL"
/data/data/com.termux/files/usr/bin/bash
```

Why? Do you have idea?

**Comment by WMCB-Tech** [comment]
proot-distro binds all possible android partitions and termux files unless isolated is specified

and yeah it would be nice to add bind mount configuration feature like the feature in chrome os named "Share with Linux"

**Comment by gyurmogyuri** [comment]
ok, but how can I access for my mounted ext4 partition in /mnt/media_rw/sdcard1 ?

**Comment by WMCB-Tech** [comment]
Seems you can't just bind mount ext4 external drives in proot nor in Termux without Android Permission, 

And i thibk it's not possible to mount/connect such ext4 devices in Android if you don't have root

**Comment by RalfWerner** [comment]
> ok, but how can I access for my mounted ext4 partition in /mnt/media_rw/sdcard1 ?

@gyurmogyuri with `df|grep rw` you find `/storage/*` and with `proot -p /storage ...` you've access like in termux

**Comment by gyurmogyuri** [comment]
> @gyurmogyuri with `df|grep rw` you find `/storage/*` and with `proot -p /storage ...` you've access like in termux
@RalfWerner I cannot use /storage I have different file system as root and as user.

> Alternative is to edit the `proot-distro` script and add Android's `/mnt` Bind Mount
@WMCB-Tech Thanks for you. I did it:
```
$ nano /data/data/com.termux/files/usr/bin/proot-distro
line 780: 			set -- "--bind=/storage" "$@"
line 781 add:  			set -- "--bind=/mnt" "$@"
```
Thanks, solved

**Comment by RalfWerner** [comment]
> I cannot use `/storage` I have different file system as root and as user.

You seem to have a _rooted device_ where the `sdcard1` is _**not**_ linked in `/storage` (see `df|grep rw`). I've been using different ubuntu/debian Arch-versions on _non-rooted devices_ with `proot` for two years and hadn't noticed any differences to _termux._
_**Nice, when you're glad with you solution!**_

I try to avoid `proot` if possible, because compared to _direct termux_ a [loss factor](https://github.com/RalfWerner/integrated-process/issues/2#issuecomment-560491552) of 0.3-6 occurs.
