### ISSUE TITLE
proot info: vpid 1: terminated with signal 11

### ISSUE THREAD

**Issue by SDRausty** [termux/proot#141]
> proot info: vpid 1: terminated with signal 11

steps to reproduce with Android 10 armv7l:

[`setupTermuxArch v i x86`](https://raw.githubusercontent.com/TermuxArch/TermuxArch/master/setupTermuxArch)

**Comment by SDRausty** [comment]
https://github.com/termux/termux-packages/issues/6141

**Comment by SDRausty** [comment]
> steps to reproduce with Android 10 armv7l:

> [`setupTermuxArch v i x86`](https://raw.githubusercontent.com/TermuxArch/TermuxArch/master/setupTermuxArch)

**Comment by SDRausty** [comment]
This is the output with 'proot  --verbose=2':

$ x86/startarch+x86
proot info: binding = /sys
proot info: binding = /data/data/com.termux/files/home/x86/var/binds/fbindprocstat:/proc/stat
proot info: binding = /data/data/com.termux/files/home/x86/tmp:/dev/shm
proot info: binding = /data/data/com.termux/files/home/x86/var/binds/fbindprocuptime:/proc/uptime
proot info: binding = /storage/emulated/0:/sdcard
proot info: binding = /data/data/com.termux/files/home
proot info: binding = /storage
proot info: binding = /data/data/com.termux/files/usr
proot info: binding = /dev/urandom:/dev/random
proot info: binding = /dev/pts/30:/proc/19717/fd/0
proot info: binding = /dev/pts/30:/proc/19717/fd/1
proot info: binding = /dev/pts/30:/proc/19717/fd/2
proot info: binding = /proc/19717/fd
proot info: binding = /system
proot info: binding = /vendor
proot info: binding = /dev/ashmem
proot info: binding = /dev
proot info: binding = /apex
proot info: binding = /dev/null:/etc/ld.so.preload
proot info: binding = /:/host-rootfs
proot info: binding = /data/data/com.termux/files/home/x86/var/binds/fbindprocversion:/proc/version
proot info: binding = /data/data/com.termux/files/home/x86/var/binds/fbindprocshmem:/proc/shmem
proot info: binding = /data/data/com.termux/files/home/x86/var/binds/fbindprocpcidevices:/proc/bus/pci/devices
proot info: binding = /data/data/com.termux/files/usr/tmp/proot-19717-PkqvEe:/proc/bus/pci
proot info: binding = /proc
proot info: binding = /data/data/com.termux/files/home/x86:/
proot info: vpid 1: translate("/" + "/usr/bin/env")
proot info: vpid 1:          -> "/data/data/com.termux/files/home/x86/usr/bin/env"
proot info: vpid 1: translate("/" + "/usr/bin/env")
proot info: vpid 1:          -> "/data/data/com.termux/files/home/x86/usr/bin/env"
proot info: host rootfs = /host-rootfs
proot info: glue rootfs = /data/data/com.termux/files/usr/tmp/proot-19717-PkqvEe
proot info: exe = /usr/bin/env
proot info: argv = /usr/bin/env -i HOME=/root TERM=xterm-256color TMPDIR=/tmp ANDROID_DATA=/data /bin/bash -l
proot info: qemu = /data/data/com.termux/files/usr/bin/qemu-i386
proot info: initial cwd = /root
proot info: verbose level = 2
proot info: pid 19717: access to "/dev/pts/30" (fd 0) won't be translated until closed
proot info: pid 19717: access to "/dev/pts/30" (fd 1) won't be translated until closed
proot info: pid 19717: access to "/dev/pts/30" (fd 2) won't be translated until closed
proot info: pid 19717: access to "/proc/19717/fd" (fd 3) won't be translated until closed
proot info: vpid 1: translate("/" + "/usr/bin/env")
proot info: vpid 1:          -> "/data/data/com.termux/files/home/x86/usr/bin/env"
proot info: vpid 1: translate("/" + "/host-rootfs/system/bin/linker")
proot info: vpid 1:          -> "/apex/com.android.runtime/bin/linker"
proot info: ptrace acceleration (seccomp mode 2, new syscall order) enabled
proot info: vpid 1: translate("/" + "/host-rootfs/data/data/com.termux/files/usr/bin/qemu-i386")
proot info: vpid 1:          -> "/data/data/com.termux/files/usr/bin/qemu-i386"
proot info: vpid 1: translate("/" + "/usr/bin/env")
proot info: vpid 1:          -> "/data/data/com.termux/files/home/x86/usr/bin/env"
proot info: vpid 1: terminated with signal 11
proot info: terminating all tracees on exit
startarch+x86  2.0.993: DONE 🏁

**Comment by xeffyr** [comment]
@SDRausty Could you try upgrading to the latest version (which is `1:5.2.0-2`) of `qemu-user-i386` package? These are chances that your issue was related to https://github.com/termux/termux-packages/issues/6172 which should be fixed now.

**Comment by melvilli** [comment]
Hello, I had exactly same issue for running ubuntu through proot on
`Linux localhost 3.4.113-lineageos armv7l Android`

Now I'm terribly sorry for the form of this message as this is the first time I'm actually writing a comment on GitHub and I have no idea on markup(?) syntax either.

It turned out that `tar` was not able to extract the root fs .tar.gz/xz files and throwing permission denied for every file when I checked via verbose extraction.. 


What I did to solve - 

Create root fs folder manually and do `chmod -R 777 (distro)-fs`, `chmod +rx (gz/xz file)` and extract all the files manually myself and run the startup script (I have used andronix ubuntu 18)

AND

Alongnside it, I compiled proot locally with a patch from this [#107 (comment)](https://github.com/termux/proot/issues/107#issuecomment-630365545) 

Now I have absolutely no expertise or knowledge to say either one worked or both are required. Pls ask me for any details about this as I'm also facing this now regardless of the distro (ubuntu which I manually installed before still works with both local or binary(?) from termux repo but no other ones work)
Thanks for keeping up with me.

**Comment by SDRausty** [comment]
> latest version (which is 1:5.2.0-2) of qemu-user-i386 package

`qemu-user-i386/stable,now 1:5.2.0-2 aarch64 [installed]`

This error only occurs on armv7l architecture.  Aarch64 qemu-i386 works as expected.

**Comment by SDRausty** [comment]
> These are chances that your issue was related to termux/termux-packages#6172 which should be fixed now.

@xeffyr This error continues to only occurs on armv7l architecture. Aarch64 qemu-i386 works as expected.

**Comment by SDRausty** [comment]
> These are chances that your issue was related to termux/termux-packages#6172 which should be fixed now.

@xeffyr This error continues only to occur on armv7l architecture; aarch64 `qemu-user-i386` and `qemu-user-x86_64` architecture packages work as expected.

**Comment by michalbednarski** [comment]
Workaround https://github.com/termux/proot/issues/107#issuecomment-630365545 can be used here (although probably for qemu proot loader could be skipped altogether)

**Comment by SDRausty** [comment]
> qemu proot loader

Armv7l: Signal 11 occurrs only with qemu-user-i386/x86_64 on armv7l architecture with PRoot.  Termux PRoot without QEMU support works fine.

Aarch64: OK

**Comment by SDRausty** [comment]
This error is now resolved; Thank you for fixing it 🎵 🎶

**Comment by androexp3rt** [comment]
I installed alpine using proot-distro package on termux and the installation went fine but error in login.
Steps:
pkg install proot-distro
pd install alpine
pd login alpine
proot info: vpid 1: terminated with signal 11


~ $ pd install alpine

Error: distribution 'alpine' is already installed.

Log in:     proot-distro login alpine
Reinstall:  proot-distro reset alpine
Uninstall:  proot-distro remove alpine

~ $ pd login alpine
proot info: vpid 1: terminated with signal 11
~ $
