### ISSUE TITLE
Sudo works incorrectly? when using it with qemu-user emulation

### ISSUE THREAD

**Issue by WMCB-Tech** [termux/proot#143]
*Originally Referenced on [proot-distro #48](https://github.com/termux/proot-distro/issues/48#issuecomment-751933663)*

sudo gives me errors about setuid even though the permissions are correct when running proot-distro with qemu user emulation
```
❯ proot-distro login ubuntu-18.04 --user marcusz ### This is x86 ubuntu
marcusz@localhost:~$ /usr/bin/sudo
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
marcusz@localhost:~$
```

**Steps to Reproduce this problem**
1. Install i386 environment (proot-distro)
2. Install sudo
3. Add user account and the user to sudoers (not usermod)
4. Log in as user
5. Test sudo `sudo test`

And it should give setuid error even with the correct permission

Reproducing this problem without qemu (or using native architecture) does not occur this problem

**Comment by michalbednarski** [comment]
It looks like PRoot currently [checks set-uidness](https://github.com/termux/proot/blob/336f4787d64e377039143ad2a50139aee4e10ad4/src/extension/fake_id0/fake_id0.c#L1058) of qemu binary, not sudo.

Since it seems (to me) that fixing this is not hard yet not trivial, I'll try making this "good first issue" as I think fixing this would be nice introduction to proot code. (If there won't be anyone willing to try this I'll fix that myself later, but I think this is nice occasion to try)

I think real path to executed binary could be taken from `tracee->raw_path` and translating it or could be saved in `expand_runner` before it is replaced.

**Comment by WMCB-Tech** [comment]
Ok, so setting the permission of qemu user binary as setuid has some weird effects, so if logging in as user, then it still logged in as root but some programs may have treated that the user is root (chown, adduser) and some programs like dpkg treats the user as regular user, but it's kinda better than getting privilege error

![Screenshot_2021-03-13-15-29-54-09.jpg](https://user-images.githubusercontent.com/65075766/111023478-39457e00-8414-11eb-8a66-c53f1eb81bfe.jpg)

**Comment by michalbednarski** [comment]
What you are showing is effect of distinction between real and effective uid (same thing would occur on normal Linux if you'd make all binaries suid).

When set-uid program is being executed, effective uid is set to root (or another owner of file in actual Linux) while real uid stays same.

* `dpkg`, `$USER` check real uid
* `whoami` checks effective uid
* `id` will show `uid=` for real uid and if effective uid is different it'll also show `euid=`

**Comment by WMCB-Tech** [comment]
Huh i see, i thought there will be a workaround if i set the qemu binary as setuid, but it didn't, and gives weird results

**Comment by WMCB-Tech** [comment]
I think i found a _workaround_ here,

since proot is able to run native binaries on emulated environment, i was able to run busybox arm64 static `su` and do `root` operations here and it works

![Screenshot_2021-04-01-14-21-26-45.jpg](https://user-images.githubusercontent.com/65075766/113251998-ce41e580-92f5-11eb-842e-4dda673be411.jpg)

**Comment by WMCB-Tech** [comment]
I also found another solution by running an SSH server as root, and login to ssh root user to gain root access,

I had to function ssh as sudo so i could easily run commands as root under qemu:

```
sudo(){ ssh root@localhost -p <port> "$@" }; 
```

**Comment by michalbednarski** [comment]
This was now fixed as part of #195

(Although it also means that `good first issue` experiment has failed...)

**Comment by SDRausty** [comment]
>(Although it also means that good first issue experiment has failed...)

Maybe this issue should have been advertised in the install script?

**Comment by SDRausty** [comment]
>(Although it also means that good first issue experiment has failed...)

[\_PRINTPROOTERROR\_](https://github.com/TermuxArch/TermuxArch/blob/master/printoutstatements.bash#L231)
```
$ grep _PRINTPROOTERROR_ *h
maintenanceroutines.bash:84:"$INSTALLDIR/$STARTBIN" || _PRINTPROOTERROR_
maintenanceroutines.bash:122:$INSTALLDIR/root/bin/setupbin.bash || _PRINTPROOTERROR_
maintenanceroutines.bash:143:$STARTBIN || _PRINTPROOTERROR_
necessaryfunctions.bash:227:"$INSTALLDIR/$STARTBIN" || _PRINTPROOTERROR_
necessaryfunctions.bash:544:"$INSTALLDIR"/root/bin/setupbin.bash || _PRINTPROOTERROR_
printoutstatements.bash:231:_PRINTPROOTERROR_() {
```
Maybe good first issue should have been advertised in the install script?

**Comment by WMCB-Tech** [comment]
It looks like i didn't notice this issue fixed, thanks
