### ISSUE TITLE
I am getting this error when I try to install the modded Version of Manjaro

### ISSUE THREAD

**Issue by Tesirfsm** [termux/proot#144]
$ ./start-androjaro.sh
proot error: '/data/data/com.termux/files/home/androjaro-fs/usr/bin/env' is a 64-bit program whereas this version of proot handles 32-bit programs only
proot info: vpid 1: terminated with signal 4
$``

I am using a Nokia 2

**Comment by xeffyr** [comment]
You need to install a 32-bit version of Manjaro.
