### ISSUE TITLE
How do i automatically log into proot at termux startup ( Question )

### ISSUE THREAD

**Issue by xd003** [termux/proot#146]
Just as the title suggests  , i just want to log into the ubuntu proot automatically at termux startup
I tried appending ```proot-distro login ubuntu-20.04``` in my .zshrc file ( i am using zsh so there's no bashrc file ) but it doesn't seem to help .
Can anyone please tell the correct way to achieve this ?

**Comment by ZhymabekRoman** [comment]
Instead of typing ```proot-distro login ubuntu-20.04``` every time, you can just add it to the .bashrc. You can type ```nano .bashrc``` in your home directory and then type this: ```proot-distro login ubuntu-20.04```.
If the previous method does not work, you can open the ```/data/data/com.termux/files/usr/bin/login``` file using ```nano``` and add exactly on the second line ```proot-distro login ubuntu-20.04```

**Comment by xd003** [comment]
@ZhymabekRoman thanks for help 
Since i was using zsh , i had .zshrc file so appending ```proot-distro login ubuntu-20.04``` in zshrc didn't seemed to work

Although your second method of removing all content of ```data/data/com.termux/files/usr/bin/login``` except first line and appending proot login did worked well 

Although i noticed after i click on termux , it takes around 3 seconds to load . Not really sure if this load time is normal or it should have been better

**Comment by WMCB-Tech** [comment]
Try specifying it on `.zshenv` or `.profile`

**Comment by WMCB-Tech** [comment]
@xd003 Try specifying your proot launch command in `$PREFIX/etc/profile.d`

**Comment by ZhymabekRoman** [comment]
> Although your second method of removing all content of ```data/data/com.termux/files/usr/bin/login``` except first line and appending proot login in 2nd line did worked well 

Are you sure? Maybe you just didn't notice. This method works fine for me

**Comment by xd003** [comment]
> > Although your second method of removing all content of ```data/data/com.termux/files/usr/bin/login``` except first line and appending proot login in 2nd line did worked well 
> 
> Are you sure? Maybe you just didn't notice. This method works fine for me 
> 
> 

I am sorry but i think there's a bit of confusion xd. I already told the second method of /usr/bin/login works . I am just saying that proot login isn't as instant or fast like loading Termux natively , it takes around 2,3 seconds. I am now beginning to beleive that's normal

**Comment by xd003** [comment]
> @xd003 Try specifying your proot launch command in `$PREFIX/etc/profile.d`
> 
> I tested it (i am using zsh just like yours) and proot-distro autostarts within zsh
> 
> Caveat:
> `echo "proot-distro login ubuntu-20.04" > $PREFIX/etc/profile.d/proot-autostart.sh`
> 
> Although in some scenarios, you may have to use `emulate` command as well

Thanks both of your suggestions work pretty well too. I think i will close this issue concluding that logging into proot can't be as fast as loading termux natively and its bound to take a 2,3 seconds
