### ISSUE TITLE
Git clone fails in openSUSE with Operation not permitted

### ISSUE THREAD

**Issue by radumamy** [termux/proot#152]
Good evening. 

Could I please report the below error? 

I am certain this worked fine on Android 10. I have tried a fresh Termux install and no joy. Also reported here https://github.com/radumamy/Termux-openSUSE/issues/1 

openSUSE Tumbleweed 20210223 container 
Linux localhost 4.19.125-perf+ #1 SMP PREEMPT Tue Feb 2 18:56:12 JST 2021 aarch64 Android
Android 11
Termux 0.108
Proot 0729cb17

`radumamy@localhost:~> git clone https://github.com/neovim/neovim.git
Cloning into 'neovim'...                                warning: unable to access '/home/radumamy/neovim/.git/config': Operation not permitted                          fatal: unknown error occurred while reading the configuration file`

**Comment by michalbednarski** [comment]
Turns out I've already had this fixed in proot repo (as 16f235f624931b3a9d96a2b6b2d687ed3d172852, although hadn't it recognized as functional fix), just not released to apt repo, where update should be soon available.

**Comment by radumamy** [comment]
Excellent. Thank you @michalbednarski.
