### ISSUE TITLE
Linker error 

### ISSUE THREAD

**Issue by Hax4us** [termux/proot#16]
I were compiling from source but stuck at this 
```undefined reference to `process_vm_writev'
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)```

**Comment by michalbednarski** [comment]
This message is part of feature detection (Like checks in `./configure` in other programs) and not actual error, real error will be probably below

**Comment by Hax4us** [comment]
Compiled now I thought it is actual error..
Thnx :)

**Comment by sdrausty** [comment]
How did you compile it?
