### ISSUE TITLE
Proot 

### ISSUE THREAD

**Issue by MasumB2** [termux/proot#169]
![Screenshot_20210624-232730_Termux](https://user-images.githubusercontent.com/77373337/123308581-a903f280-d545-11eb-83fa-e25a4532bea2.jpg)
root error: execve("/usr/bin/env"): No such file or dir ctory

root info: It seems that termux-exec is active and is p epending /data/data/com.termux/... to executable paths f this is path is not available inside proot, please "u

set LD_PRELOAD"

atal error: see proot --help`.

root error: can't chmod '/data/data/com.termux/files/us

/tmp/proot-18482-jTUgDv': No such file or directory

root error: can't chdir to: No such file or director

**Comment by MasumB2** [comment]
How to slove this please tell me!

**Comment by WMCB-Tech** [comment]
The error message literally says and provided the solution

`unset LD_PRELOAD` first before using `proot
