### ISSUE TITLE
VNC don't work in Ubuntu 20.04

### ISSUE THREAD

**Issue by Pedro1234-code** [termux/proot#170]
When I install xfce in Ubuntu 20.04 proot-distro and try to login in VNC Viewer, it loses the connection.

**Comment by ZhymabekRoman** [comment]
> When I install xfce in Ubuntu 20.04 proot-distro and try to login in VNC Viewer

Any error?

> it loses the connection.

screenshot please

**Comment by Yonle** [comment]
Are you sure that your connection address that you tried to connect is correct? Please make sure everything is correct. If your vnc server is listening on localhost:1, Then you should connect to `localhost:5901`. Else, If it listen to `localhost:2` or something like that, You should connect to `localhost:5902` or else in your VNC Viewer like that.

Also do not forget to check logs at `.vnc/*.log`

**Comment by Pedro1234-code** [comment]
Yes, I am sure. When I install the same operating system (Ubuntu) with Andronix, It Works. This bug is happening only with proot-distro.

**Comment by xeffyr** [comment]
@Pedro1234-code Do you have any logs which will help to understand the issue?

One of proot-distro differences from Andronix is use of unstable proot extension "--sysvipc" by default. You can try to disable it:
```
proot-distro login --no-sysvipc ubuntu-20.04
```

**Comment by Grimler91** [comment]
Closing since the issue hasn't been updated. Please provide logs if this is still a problem (see [bug report template](https://github.com/termux/proot/issues/new?assignees=&labels=&template=bug_report.md))
