### ISSUE TITLE
Chromium not starting on ubuntu 20.04

### ISSUE THREAD

**Issue by Pedro1234-code** [termux/proot#178]
**Problem description**

Chromium isn't running on Ubuntu 20.04 PRoot, but I don't know if it's happening because my phone only have 2gb of RAM.
**Steps to reproduce**

Run Ubuntu 20.04, start VNC Server, login to VNC and start Chromium.
**Expected behavior**

Run chromium
**Additional information**

```
Packages CPU architecture:
armhf
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
Updatable packages:
termux-tools/stable 0.134-1 all [upgradable from: 0.133-1]
Android version:
10
Kernel build information:
Linux 4.10.5+ #1 SMP Fri Jul 23 10:06:55 PDT 2021 armv81 Android
Device manufacturer:
Samsung

Device model:
A10
```

**Comment by ZhymabekRoman** [comment]
Specifically, how does chromium not start? Show "Segmentation fault"?

**Comment by ZhymabekRoman** [comment]
> @ZhymabekRoman Yes, terminal is showing "Segmentation fault".

See https://github.com/termux/proot/issues/107
Need recompile proot from source, or just use Firefox ESR
