### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by Hax4us** [termux/proot#18]
Recently I installed Kali nethunter like as Arch Linux in termux using proot
But after apt-get upgrade I am getting this error
```
Unpacking perl (5.26.1-5) over (5.26.0-8) ...
dpkg: error processing archive /tmp/apt-dpkg-install-7cd3oB/0-perl_5.26.1-5_arm64.deb (--unpack):
 unable to securely remove '/usr/bin/corelist.dpkg-tmp': Operation not permitted
Preparing to unpack .../1-perl-modules-5.26_5.26.1-5_all.deb ...
```
And above error is coming each time whenever any package is trying to upgrade itself it means that if any package i.e, perl is already installed but I am trying to upgrade perl .

Above error is only happening in aarch64 devices not in armhf devices idk why

Any workaround suggestions ?

**Comment by Hax4us** [comment]
I found that apt was trying to remove corelist.dpkg-tmp from /usr/bin while upgrading perl and it is root cause because I tried to remove manually but can't remove
```
rm /usr/bin/corelist.dpkg-tmp
rm: cannot remove '/usr/bin/corelist.dpkg-tmp': Operation not permitted
```
And I got very strange output of ls -l in /usr/bin
```
l?????????? ? ?    ?          ?            ? corelist.dpkg-tmp
```
And here is output of file command
```
file kali-arm64/usr/bin/corelist.dpkg-tmp
kali-arm64/usr/bin/corelist.dpkg-tmp: broken symbolic link to /data/data/com.termux/files/home/kali-arm64/usr/bin/.l2s.corelist0001
```

**Comment by Hax4us** [comment]
Yes , working in armhf but not in aarch64 ... Well now I can pray lol

**Comment by sdrausty** [comment]
Why is the building failed monthly?

**Comment by Hax4us** [comment]
It is happening again but idk why it is working in my phone only

**Comment by Hax4us** [comment]
![img_20180602_161737_477](https://user-images.githubusercontent.com/30441647/40873582-a4220b12-6680-11e8-89ef-65132064d1f0.jpg)
There are some broken links exist after extraction of Kali tar file but strange in my phone there is no any broken link present and actually only in my phone ..... I tried with more than 5 phones but same results

**Comment by Hax4us** [comment]
Solved
