### ISSUE TITLE
Undeclared variable ARG_MAX

### ISSUE THREAD

**Issue by Hax4us** [termux/proot#20]
```
$ cat cli.c | grep ARG
#include <linux/limits.h>  /* ARG_MAX, PATH_MAX, */
        char string[ARG_MAX] = "";
```
and idk how but suddenly I am facing this error while compiling proot from source 
```
./cli/cli.c:164:14: error: use of
      undeclared identifier 'ARG_MAX'
        char string[ARG_MAX] = "";
                    ^
```
So when I checked `linux/limits.h` file for __ARG_MAX__ declaration so I found nothing .

**Comment by Hax4us** [comment]
I am still facing same error .. Am I missing something ?

**Comment by Hax4us** [comment]
```
$ getconf ARG_MAX
4096
```
But there is no any declaration in linux/limits.h

**Comment by michalbednarski** [comment]
I'm generally building proot through termux-packages, not on device so I don't know. In NDK there's:
```
ndk-bundle/sysroot/usr/include/linux/limits.h:#define** ARG_MAX 131072
```

**Comment by Hax4us** [comment]
😶its very strange bcz I compiled it yesterday without any this error

**Comment by Grimler91** [comment]
```
grep -r ARG_MAX $PREFIX/include
/data/data/com.termux/files/usr/include/bits/sysconf.h:#define _SC_ARG_MAX 0x0000
/data/data/com.termux/files/usr/include/bits/posix_limits.h:#define _POSIX_ARG_MAX 4096
/data/data/com.termux/files/usr/include/linux/limits.h:#define _KERNEL_ARG_MAX 131072
```

I guess it's called _KERNEL_ARG_MAX on device.

**Comment by Hax4us** [comment]
Yes you are right  @Grimler91 https://github.com/urho3d/android-ndk/blob/master/platforms/android-17/arch-arm/usr/include/linux/limits.h
