### ISSUE TITLE
Warning: no /bin/su available in rootfs!

### ISSUE THREAD

**Issue by essential-existence** [termux/proot#206]
There was no such error before:

> proot-distro install alpine
> proot-distro login alpine
Warning: no /bin/su available in rootfs!
localhost:~#

termux 0.117

**Comment by xeffyr** [comment]
`apk add shadow`

**Comment by essential-existence** [comment]
> `apk add shadow`

Yes it solved the problem!
But why? Was the "shadow" package removed from this version of the distribution?
Thanks!

**Comment by xeffyr** [comment]
PRoot Distro started to check `/bin/su` existence since 2.9.0, though this check didn't worked properly if `/bin/su` was a symlink. This should be fixed in `proot-distro` package version 2.9.2 and yes, Alpine Linux doesn't have lots of packages preinstalled (that's why it is so small).
