### ISSUE TITLE
How to use vscode in armv8l

### ISSUE THREAD

**Issue by TranCongVinh** [termux/proot#211]
I got segmentation fault when try to open.

**Comment by ZhymabekRoman** [comment]
Use VIM

**Comment by thunder-coding** [comment]
@TranCongVinh Consider moving to GitHub Discussions and use the bug tracker only for reporting issues

**Comment by michalbednarski** [comment]
vscode segfault on armv8l, got it (though it might take some time to actually fix)

While I'll yet have to check this particular issue, chances are these segfaults are loader clashes as described #107 (Yeah, I should have move that loader in official version)

Long time ago there were also successful (as far as I remember) attempts to use Theia IDE (which as far as I know is related to Code but not using Electron, although I haven't used neither so don't really know) in #28, you might want to try if it is suitable replacement

> Use VIM

I think this comment isn't really useful, user of proot probably knows already about VIMs existence and wanted to use something else. Also I'm assuming that issue author had already working X and has problem with vscode in particular

**Comment by michalbednarski** [comment]
Also, what did you use to install code?

**Comment by WMCB-Tech** [comment]
VS Code is installed through official Microsoft website. they provide arm packages

**Comment by TranCongVinh** [comment]
;-;

**Comment by TranCongVinh** [comment]
> Also, what did you use to install code?

wget vscode; dpkg -i vscode.deb
kali@localhost:~$code
 loser ;-;

I tried to edit the loader address to 0x20000000
And it doesnt give segmentation fault but vscose not start ;-;.

**Comment by WMCB-Tech** [comment]
> And it doesnt give segmentation fault but vscode not start ;-;.

What do you mean by "not start"?
Can you post some logs of an actual error

**Comment by TranCongVinh** [comment]
> > And it doesnt give segmentation fault but vscode not start ;-;.
> 
> What do you mean by "not start"? Can you post some logs of an actual error

;-; bad english, sorry

**Comment by TranCongVinh** [comment]
normal proot : segfault
loader address to 0x20000000 : grep: /proc/version permisson denied

**Comment by WMCB-Tech** [comment]
Have you tried code with `--no-sandbox` as well?

**Comment by TranCongVinh** [comment]
> 
Its working, thank Marcusz
And can u tell me wat does --no-sandbox does

**Comment by michalbednarski** [comment]
--no-sandbox disables Chromium sandbox, which currently isn't working
inside proot (Chromium (and therefore also Electron)) attempts to chroot
into /proc subdirectory, which isn't supported inside proot, as well as few
other things)

Anyway are you saying that it was necessary to move loader to 0x20000000 in
order to run vscode?

Regarding /proc/version issues these need to be handled by proot
wrapper/user by providing own /proc/version file through --bind argument

**Comment by TranCongVinh** [comment]
> Anyway are you saying that it was necessary to move loader to 0x20000000 in
order to run vscode?
Yes
