### ISSUE TITLE
signal 7 when running Ancient Domains Of Mystery (ADOM)

### ISSUE THREAD

**Issue by alextirzx** [termux/proot#233]
Trying to run ADOM  following this article:
https://archenoth.com/tech/2020/05/29/Roguelikes-in-Termux.html

I always run into this error (proot info: vpid 1: terminated with signal 7) with no idea on what is causing it or how to fix it

I have some very  basic programming knowledge but this is new and completely unknown for me

**Comment by michalbednarski** [comment]
I was able to get it running using following commands (from linked article, using version for Raspberry, adom needs to be extracted in Termux home directory (not /sdcard), using proot without qemu):

```
wget https://www.adom.de/home/download/current/adom_linux_arm_3.3.3.tar.gz
tar xvaf adom_linux_arm_3.3.3.tar.gz
cd adom
TERMINFO=/data/data/com.termux/files/usr/share/terminfo TERM=xterm proot ./adom
```

If that still doesn't work then this is probably device-specific issue and I'd need you to capture logs and attach them to this issue:
```
script output.txt -c 'uname -a ; env TERMINFO=/data/data/com.termux/files/usr/share/terminfo TERM=xterm proot -v 9 ./adom'
```

**Comment by alextirzx** [comment]
Thanks a lot for the help, I got it running with some help from Reddit (using the commands you recommended me to use)
