### ISSUE TITLE
Proot Java error

### ISSUE THREAD

**Issue by yash2120s** [termux/proot#236]
Sir please help me when i run termux-chroot then it comes -
And after I run java or apktool so this comes - proot info: vpid 1: terminated with signal 4
proot error: '/data/data/com.termux/files/usr/share/jdk8/bin/java' is a 64-bit program whereas this version of proot handles 32-bit programs only
please help me how to solve it

**Comment by wmcbtech30** [comment]
It appears to load java 64-bit binary but your proot installation is 32-bit or something else, although your issue lacks of information (missing `termux-info` output), however based on your error it executes java version 8 while we have java 17 in our packages. please install openjdk via `apt install openjdk-17`. btw we also have apktool and can be installed via `apt install apktool`
