### ISSUE TITLE
system bus emulation for Seamonkey AArch64

### ISSUE THREAD

**Issue by JanuszChmiel** [termux/proot#242]
Dear elite Proot programmers,
Seamonkey 2.53.1 aarch64 require system bus connection. So Seamonkey can not be used, this have not been true on its previous versions.
Please could you try to emulate some system bus feetback for Seamonkey, so it could be used?
Or Proot really can not do such thinks?
I have studied command line options for Semaonkey but none of those options can disable this behaviour.
I AM very sad, because Seamonkey have been so good?
Or how could i use older Seamonkey, if Arch Linux community repository contain newest and it is very probably impossible to use older release, which did not depend on system bus.
Thank you very much for your help.

**Comment by michalbednarski** [comment]
I'm not actually sure why is that, but it appears that prebuilt seamonkey from aarch64 archlinux is broken even when running in chroot on raspi (without proot), while seamonkey built from source appears to work inside proot

**Comment by JanuszChmiel** [comment]
Dear MR bednarski,
And do you think, that there is there any chance to build so complex package on The phone with 8 core CPU and with only 4 GB of RAM? Or which device would be usable for building Seamonkey from source to get it work normally? It is very probably not possible to find precompiled older binaryes because I do not have The problems to use older but rather functioning one instead of up to date and which do not work. But I AM afraid, that if I would try to build so complex package as Seamonkey on Phone, that I could burn out all chips, because it could take too much time. Sure, if I would own other phone than Huawei, which required Proot work arounds to overcome file system file naming problems, may be, that I could have some chance. Seamonkey contain faster Gecko build in rendering engine and it is much faster with Orca. No so much shared memory calls is also implemented so I prefer Seamonkey when running in Chroot. If you would have some time dear elite MR bednarski, could you try to build Seamonkey on Termux and Proot to find out, if it would be possible?
Thank you very very much.
