### ISSUE TITLE
 Permission denied 

### ISSUE THREAD

**Issue by Lucifer-Ak-MorningStar** [termux/proot#253]
bash: cd: etc: Permission denied
bash: cd: bin: Permission denied
bash: cd: tmp: Permission denied
bash: cd: var: Permission denied
When I type (cd etc) or (cd bin) or (cd tmp) or (cd var) nothing opens

**Comment by Grimler91** [comment]
I see no indication that this is a proot issue (use the [bug report template](https://github.com/termux/proot/issues/new?assignees=&labels=&template=bug_report.md))
