### ISSUE TITLE
`WARNING: linker: Warning: failed to find generated linker configuration from "/linkerconfig/ld.config.txt"` on Android 12+

### ISSUE THREAD

**Issue by TheBrokenRail** [termux/proot#254]
**Problem description**
When starting anything with PRoot, the linker gives the warning:
```
WARNING: linker: Warning: failed to find generated linker configuration from "/linkerconfig/ld.config.txt"
```

[Here's running it with debug logging.](https://gist.github.com/TheBrokenRail/70a6fde30296168d4df5c36dc5c26d44)

**Steps to reproduce**
1. Use a device with Android 12+
2. Run `proot true`

**Expected behavior**
No warning appears.

**Additional information**
```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
1.36.1
Android version:
13
Kernel build information:
Linux localhost 5.4.147-qgki-25323472-abG991USQS5DVL1 #1 SMP PREEMPT Mon Dec 5 18:27:06 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G991U
```

The error is also referenced [here](https://github.com/termux/proot-distro#known-issues).

After some investigation, it appears to orrignate from [here](https://github.com/termux/proot/blob/5c462a6ecfddd629b1439f38fbb61216d6fcb359/src/path/canon.c#L159). It seems to be trying to check whether `/linkerconfig` is a directory, but `lstat` fails with `EACCES`.

I created a patch to temporaily workaround this, but a proper solution would probably be preferable:
```patch
--- proot/src/path/canon.c
+++ proot/src/path/canon.c
@@ -155,6 +155,9 @@ static inline int substitute_binding_stat(Tracee *tracee, Finality finality, uns
 	statl.st_mode = 0;
 	if (should_skip_file_access_due_to_f2fs_bug(tracee, host_path)) {
 		status = -ENOENT;
+	} else if (strcmp(host_path, "/linkerconfig") == 0) {
+		status = 0;
+		statl.st_mode = S_IFDIR;
 	} else {
 		status = lstat(host_path, &statl);
 	}
```

**Comment by michalbednarski** [comment]
Thanks for figuring out issue and providing patch

Integrated in 0fdcda1d302dd05c175f250f2dd06c90c4e255cb with difference to always perform `lstat()` and only use hardcoded value if access was denied

I guess there's no better way of handling that

**Comment by michalbednarski** [comment]
Updated version is now available in Termux apt repo

Thanks for finding the issue and providing fix
