### ISSUE TITLE
Bad address error while executing tar 

### ISSUE THREAD

**Issue by Hax4us** [termux/proot#27]
Original issue https://github.com/Hax4us/Nethunter-In-Termux/issues/57
And it is happening with some phones having aarch64 5.1.1 Android so its not specific to Oreo
![43327334-728ae752-91bb-11e8-9bf0-8870cd6f228a](https://user-images.githubusercontent.com/30441647/43328780-9d12b27c-91dc-11e8-9399-10e04d3831b7.jpg)
![43328256-d2463c80-91bd-11e8-8370-752700252a57](https://user-images.githubusercontent.com/30441647/43328811-a5a7a06e-91dc-11e8-8081-d81d24556376.jpg)
![43328427-3cc9d760-91be-11e8-820e-fc4ac929248d](https://user-images.githubusercontent.com/30441647/43328842-b3e28e32-91dc-11e8-8aad-bdfb6a1d5677.jpg)

**Comment by michalbednarski** [comment]
This is bug in Huawei kernel and there's version with workaround at #15, but so far workaround wasn't put in release.

**Comment by Hax4us** [comment]
I didn't not know , Thnx :)
