### ISSUE TITLE
Dbus service cannot be started after upgrading proot

### ISSUE THREAD

**Issue by 23xvx** [termux/proot#295]
**Problem description**
after upgrading proot to version `5.1.107-63`, dbus service cannot be started under `proot`, showing `/proc is not mounted`
![dbus_showing_error](https://github.com/termux/proot/assets/120558411/152dd3a6-9245-495c-b7a9-69ec28746f68)
i'm sure this can only be the problem of proot because the same error occurs even not using distro with `proot-distro`
however  `dbus-daemon --system` works and created a PID file.

**Steps to reproduce**
- install a distro under proot-distro
- login to it and install `dbus`
- start dbus service with `service dbus start`

**Expected behavior**
- dbus service starting normally , showing `Starting system message bus dbus`

**Additional information**
after downgrading `proot` to `5.1.107-62` , dbus service works normally
![dbus_normal](https://github.com/termux/proot/assets/120558411/cb4ce672-44d9-46cb-b85c-372d8944ac9a)
therefore i can only suspect it is the problem of `proot`

Android 13 , aarch64

**Comment by michalbednarski** [comment]
Fixed in `proot 5.1.107-64`, thanks for reporting
