### ISSUE TITLE
Complaint Regarding Installation Issues with Kali NetHunter in Termux

### ISSUE THREAD

**Issue by mdnoman028** [termux/proot#298]
Complaint Regarding Installation Issues with Kali NetHunter in Termux

Dear Support Team,

I hope this message finds you well. I am writing to express my frustration regarding ongoing issues I have encountered while attempting to install Kali NetHunter on my Android device using Termux. Despite following the recommended installation steps, I have faced persistent errors that have hindered the setup process.

Specifically, I have encountered the following errors:
- "touch: cannot touch 'kali-arm64/root/.version': No such file or directory"
- "grep: kali-arm64/etc/passwd: No such file or directory"
- "proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/kali-arm64, cwd = /root, $PATH=(null))"

I have attempted various troubleshooting steps, including updating Termux, ensuring sufficient storage space, and verifying permissions. However, these efforts have not resolved the issues.

Could you please investigate these errors and provide guidance on how to resolve them? Additionally, if there are any specific instructions or updated scripts that I should follow, please provide them.

For your reference, here are some details about my device:
- Device Model: [realme c55]
- Android Version: [13]
- Termux Version: [googleplay.07.07]

I appreciate your prompt attention to this matter and look forward to your assistance in resolving these installation issues.

Thank you for your support.

Sincerely,
[Nomi]

**Comment by twaik** [comment]
https://wiki.termux.com/wiki/Hacking
