### ISSUE TITLE
proot alpine - unable to bind to 0.0.0.0:80 permission denied

### ISSUE THREAD

**Issue by mmahdium** [termux/proot#302]
**Problem description**
Using proot-distro and alpine image, Installed Nginx and when trying to start it by `nginx` command it gives the error: `nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)`

**Steps to reproduce**
Install any distro using proot-distro and try running nginx in it

**Expected behavior**
Be able to run a web server and access it from the network to which the phone is connected to

**Additional information**
Latest termux version is used
```
Packages CPU architecture:
aarch64
termux-tools version:
1.42.4
Android version:
10
Kernel build information:
Linux localhost 4.14.116 #1 SMP PREEMPT Tue Feb 27 19:30:25 CST 2024 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
STK-L21

```

**Comment by twaik** [comment]
Proot does not allow you to bind ports below 1024 because it is not real root. P in proot stands for `pseudo`. You should use ports above 1024.
