### ISSUE TITLE
uid mess, dbus reject auth

### ISSUE THREAD

**Issue by bbqz007** [termux/proot#36]
i run desktop within my centos deploy, although the desktop can work, but also many services failed, which should be solved one by one. in this issue it is about polkitd. this program can work with my debian but centos.
the centos polkitd outputs:  

[root@localhost ~]# sudo -u root /lib/polkit-1/polkitd                                    Successfully changed to user polkitd
Error getting system bus: Exhausted all available authentication mechanisms (tried: EXTERNAL, DBUS_COOKIE_SHA1, ANONYMOUS) (available: EXTERNAL, DBUS_COOKIE_SHA1, ANONYMOUS)
** (polkitd:25985): WARNING **: Error getting system bus: Exhausted all available authentication mechanisms (tried: EXTERNAL, DBUS_COOKIE_SHA1, ANONYMOUS) (available: EXTERNAL, DBUS_COOKIE_SHA1, ANONYMOUS)
22:59:56.378: Loading rules from directory /etc/polkit-1/rules.d                          22:59:56.379: Loading rules from directory /usr/share/polkit-1/rules.d
22:59:56.407: Finished loading, compiling and executing 9 rules                           Entering main event loop
22:59:56.425: Lost the name org.freedesktop.PolicyKit1 - exiting
Shutting down

the polkitd changed to user polkitd, and failed to do auth with dbus for exhausting all auth.
in my centos, this user polkitd has uid 999. i strace into it, and see it use uid 999 to do auth with dbus, then dbus reject it.
i read the service conf in /etc/dbus/system.d, the conf file configure the user polkitd owning the service. 
the centos release make polkitd should run as user polkitd, that would be safer and i can not change it run as root. centos won't close an eye let things run as root, it strongly make things run as who the are.  something has no problem in other linux but centos.

i doubt there are no correct uid in the mind of the processes in proot container.
when i sudo -u polkitd bash and run top, all the processes change to user polkitd.
when i exit back to the root bash and run top, all the processes change to user root.

although id can recognize the correct uid what they are within a proot container, but other programs could not.

in debian, all services are configure to be owned by root. dbus seems to only deal with case of user root, it won't touch any trouble.

**Comment by bbqz007** [comment]
the problem could be simply present like that
dbus-daemon --system
sudo -u polkitd python, and use python to get a systembus connection.

**Comment by michalbednarski** [comment]
I've just pushed fb0ce67526097accece733f18161235e733e54f8 which should fix dbus issue.

> all the processes change to user polkitd

All files that are normally owned by Termux (uid outside proot) have their owner reported as uid of process calling [`stat`](http://man7.org/linux/man-pages/man2/stat.2.html) on them. This rule applies also to files in `/proc` as code replacing `stat` results doesn't check what file is being `stat`'ed; only original `st_uid` reported by kernel is checked there.
