### ISSUE TITLE
udev support

### ISSUE THREAD

**Issue by Bakaika** [termux/proot#47]

**Comment by michalbednarski** [comment]
I'm not sure what you mean, but I think this is out of scope as proot is not managing hardware but only redirecting file access.

**Comment by Bakaika** [comment]
programs that use [udev](http://manpages.ubuntu.com/manpages/xenial/man7/udev.7.html) fail to run in proot due to not having *real* root permissions. they do work when running proot as root though. ¯\_(ツ)_/¯

**Comment by Bakaika** [comment]
good point
i'll stick to qemu

> sounds interesting

**Comment by michalbednarski** [comment]
Depending on what do you need it might be possible to stub interface (so it always returns successful but empty result) in case some program fails without but you don't actually need hardware access.

If that is the case then please describe what you want to achieve and how can we test that.

**Comment by xeffyr** [comment]
> If that is the case then please describe what you want to achieve and how can we test that.

Yes, we need to know what you are trying to run. In most cases, udev is not needed to use chrooted environment unless you are trying to start something like systemd.

**Comment by michalbednarski** [comment]
I've tried Chromium and it mostly works:
* You'll need to have usable `/dev/shm`, create `fake_shm` directory and pass `-b fake_shm:/dev/shm` argument to `proot`
* `--no-sandbox` flag has to be used as chromium sandbox is not usable with proot's fake root (not sure on impact but note that proot is not security boundary and implementing uid-separation with it doesn't protect security)
* Of course you'll need X server (I've tested with `Xvnc` server and connected to it from desktop; or use headless mode, `chromium --no-sandbox --headless --screenshot https://google.com` worked for me (saved output in `screenshot.png`)

Nothing udev related had to be done (although hardware related (such as [querying battery level](https://pazguille.github.io/demo-battery-api/)) stuff might not work)

**Comment by Bakaika** [comment]
Yeah chromium mostly works.
Electron exits instead of warning, not sure how to fix that one tbh.

**Comment by michalbednarski** [comment]
`electron` also works, You'll just need to set up `/dev/shm` as described above.

**Comment by lifeModder19135** [comment]
Currently writing a udev impl that works in Termux just because it is the "right thing to do", at least by my standards. (Starting now. XD )

Edit: starting just as soon as I am done researching what a udev impl looks like...

**Comment by bbbruni** [comment]
> [michalbednarski](https://github.com/michalbednarski) commented [on 5 Nov 2018](https://github.com/termux/proot/issues/47#issuecomment-435977364)
> Depending on what do you need it might be possible to stub interface (so it always returns successful but empty result) in case some program fails without but you don't actually need hardware access.

Running an OpenGL application with wine through XServer XSDL (https://github.com/pelya/xserver-xsdl) on top of proot gives the following message:

> 0026:err:plugplay:deviceloop_thread Can't init SDL: Could not initialize UDEV
See https://github.com/ptitSeb/box86/issues/566

Wine uses udev and sdl to detect additional devices like joysticks, Bluetooth dongles, etc.
Can it be stubbed?

**Comment by wmcbtech30** [comment]
It will read external devices (joystick, dongles, etc.) yes. but you don't need udev as it will continue to work. all external devices goes to android

**Comment by wormstest** [comment]
> Running an OpenGL application with wine through XServer XSDL (https://github.com/pelya/xserver-xsdl) on top of proot gives the following message:

I not use Xserver XSDL, i use Termux-x11 (Xwayland)

**Comment by Android-PowerUser** [comment]
@lifeModder19135 did you get any further with it?
