### ISSUE TITLE
Terminated &bus error 

### ISSUE THREAD

**Issue by 9990242854** [termux/proot#53]
$ ls
parrot-binds     parrot.sh
parrot-fs        start-parrot.sh
$ ./start-parrot.sh
proot info: vpid 1: terminated with signal 11
$ export PROOT_NO_SECCOMP=1
$ ./start-parrot.sh
bash: [: : integer expression expected
proot info: vpid 1: terminated with signal 7

Your trick export PROOT_NO_SECCOMP only work one next time when i shows that.

**Comment by Grimler91** [comment]
Closing since issue has not bee updated in quite a while, please fill in the [bug report template](https://github.com/termux/proot/issues/new?assignees=&labels=&template=bug_report.md) if this is still an issue
