### ISSUE TITLE
Virtual mount

### ISSUE THREAD

**Issue by aristarh2704** [termux/proot#61]
Please, add support for virtual mount and fuse, which not require root

**Comment by xeffyr** [comment]
> and fuse

And kernel modules... in userspace.

**Comment by xeffyr** [comment]
There 2 things:

1. On Android, FUSE require root.

2. Proot uses ptrace() to hook system calls.

**Comment by aristarh2704** [comment]
But I think it's possible implement fuse over ptrace.

**Comment by michalbednarski** [comment]
It should be noted here, that while proot intercepts opening files (e.g. through `open(2)`), it does not do anything once files are opened (proot doesn't keep own file descriptor table nor intercepts `read(2)`, `lseek(2)`, etc.)

Changing proot to intercept those is probably out of scope and might affect performance.
