### ISSUE TITLE
Add Reference Wiki Page

### ISSUE THREAD

**Issue by oxr463** [termux/proot#64]
https://wiki.termux.com/wiki/PRoot

**Comment by michalbednarski** [comment]
So far this repo and that wiki were mostly independent (with wiki being about proot usage/distros and this repo issues about troubleshooting proot), but if you think wiki link in README would be useful and fitting you can send pull request.

**Comment by oxr463** [comment]
Perhaps the wiki page can be added for the website field for the repository here on GitHub.
Otherwise, I can make a PR.

**Comment by michalbednarski** [comment]
Ok, I've set project website link on GitHub to wiki
