### ISSUE TITLE
How to disable /host-rootfs with QEMU specified?

### ISSUE THREAD

**Issue by zaoqi** [termux/proot#66]
related issue: https://github.com/termux/proot/issues/67

**Comment by xeffyr** [comment]
Seems like no.
From [src/execve/enter.c#L192](https://github.com/termux/proot/blob/d9f15817f8e06e41f8c2d37f1433005c8323631e/src/execve/enter.c#L192):
```
/* When a QEMU command was specified:
 *
 * - if it's a foreign binary we are reading the ELF
 *   interpreter of QEMU instead.
 *
 * - if it's a host binary, we are reading its ELF
 *   interpreter.
 *
 * In both case, it lies in "/host-rootfs" from a guest
 * point-of-view.  */
```

**Comment by zaoqi** [comment]
It is possible: https://github.com/proot-me/proot/issues/181

**Comment by michalbednarski** [comment]
Looks like this is same underlying issue as #67, so let's continue discussion there.
