### ISSUE TITLE
$ ./start-tumbleweed.sh *** stack smashing detected ***: <unknown> terminated *** 

### ISSUE THREAD

**Issue by Kilo-411** [termux/proot#69]
> $ ./start-tumbleweed.sh
*** stack smashing detected ***: <unknown> terminated
*** stack smashing detected ***: <unknown> terminated
$

>  issues just keep coming.  I am gonna get this even if i gotta re'code the whole app.

**Comment by michalbednarski** [comment]
Could you post results of running
```
PROOT_VERBOSE=9 ./start-tumbleweed.sh
```

**Comment by Kilo-411** [comment]
t info: vpid 1: sysenter end: setpgid(0x0, 0x3d45, 0x37346a00, 0x37346a00, 0x8, 0x37918) = 0x0 [0xbe929654, 0]              proot info: vpid 1: sysexit start: setpgid(0x0, 0x3d45, 0x37346a00, 0x37346a00, 0x8, 0x37918) = 0x0 [0xbe929654, 0]             proot info: vpid 1: sysexit end: setpgid(0x0, 0x3d45, 0x37346a00, 0x37346a00, 0x8, 0x37918) = 0x0 [0xbe929654, 0]               proot info: vpid 1: sysenter start: rt_sigaction(0x7, 0xbe92940c, 0xbe929498, 0x8, 0xbe929544, 0xbe9295d0) = 0x7 [0xbe929408, 0]proot info: vpid 1: sysenter end: rt_sigactio$

**Comment by Kilo-411** [comment]
Hmm i see some unknown stuff in there.. I might have a bug in that

**Comment by michalbednarski** [comment]
Looks like this is only fragment of result (but that is log I'm looking for, just you've pasted only part of it).

Please pipe that log to file and attach it to issue (drag and drop file onto GitHub issue to attach or paste inline, but if pasting please [wrap it in backticks so it's not merged into single line](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)).

```
PROOT_VERBOSE=9 ./start-tumbleweed.sh &> trace.txt
```

**Comment by Kilo-411** [comment]
Pipe didnt work but i got it on file .

**Comment by Kilo-411** [comment]
[verbose.docx](https://github.com/termux/proot/files/3437966/verbose.docx)

**Comment by michalbednarski** [comment]
Whats wrong with `&>` pipe?

The log you've provided still is incomplete (It neither contains start of execution nor crash at end, the middle part that you've provided looks like is working correctly)

**Comment by Kilo-411** [comment]
I never said that
( 0x5410, 0xbe92952c, 0x37346a00, 0x1f0328c8, 0xbe92953c) = 0x0 [0xbe929524, 0]     proot info: vpid 1: sysexit end: ioctl(0x0, 0x5410, 0xbe92952c, 0x37346a00, 0x1f0328c8, 0xbe92953c) = 0x0 [0xbe929524, 0]       proot info: vpid 1: sysenter start: rt_sigprocmask(0x2, 0xbe9295bc, 0x0, 0x8, 0x1f0328c8, 0x0) = 0x2 [0xbe929498, 0]            proot info: vpid 1: sysenter end: rt_sigprocmask(0x2, 0xbe9295bc, 0x0, 0x8, 0x1f0328c8, 0x0) = 0x2 [0xbe929498, 0]              proot info: vpid 1: sysexit start: rt_sigprocmask(0x0, 0xbe9295bc, 0x0, 0x8, 0x1f0328c8, 0x0) = 0x0 [0xbe929498, 0]             proot info: vpid 1: sysexit end: rt_sigprocmask(0x0, 0xbe9295bc, 0x0, 0x8, 0x1f0328c8, 0x0) = 0x0 [0xbe929498, 0]               proot info: vpid 1: sysenter start: setpgid(0x0, 0x3d45, 0x37346a00, 0x37346a00, 0x8, 0x37918) = 0x0 [0xbe9296$ $ pipeNo command 'pipe' )

**Comment by Kilo-411** [comment]
<localhost:(unknown)# ps
PID   USER     TIME  COMMAND
  856 root      0:00 ps
15505 root      0:00 /data/data/com.termux/files/usr/bin/bash -
25091 root      0:00 proot --link2symlink -0 -r alpine-fs -b /d >

**Comment by michalbednarski** [comment]
Please try running

```
PROOT_VERBOSE=9 ./start-tumbleweed.sh |& busybox nc termbin.com 9999
```

And provide link that was outputted by that command

According to you first post in this issue `./start-tumbleweed.sh` crashed at beginning (without you entering further commands in shell), so this should gather necessary logs without further input.

**Comment by Kilo-411** [comment]
I did it

**Comment by michalbednarski** [comment]
I'm asking for running

```
PROOT_VERBOSE=9 ./start-tumbleweed.sh |& busybox nc termbin.com 9999
```

(your reply contained results of wrong command)
