### ISSUE TITLE
Issue with proot on android pie

### ISSUE THREAD

**Issue by strikersix23** [termux/proot#71]
Issue with proot not working with http streams causing termux arch to not install and my Ubuntu root-fs not being able to update packages

**Comment by michalbednarski** [comment]
In 387aa91bf5203d67f27a4838cfa871b657f71ce5 I've just fixed similar issue but affecting only 32bit x86. It looks like you're on 32bit arm which uses `sendmmsg` directly (not through `socketcall`) and `sendmmsg` is there allowed by Android seccomp and used by prooted glibc.

Could you try running following command and reporting result
```
echo apt update | PROOT_VERBOSE=9 ./start.sh |& busybox nc termbin.com 9999
```

**Comment by strikersix23** [comment]
Here I did what you said sorry for the late response
https://termbin.com/8dy8

**Comment by strikersix23** [comment]
Yes I'm on arm32 android 9 pie

**Comment by strikersix23** [comment]
[Uploading og1r.txt…]()
here's a better

**Comment by strikersix23** [comment]
michalbednarski your last commit does not fix it

**Comment by michalbednarski** [comment]
I think I've identified issue, pushed to `new_order_void_syscall_fix` branch (8b169bc1774d4f7277363b76ca52fceced9eaf24). Please test and if it works then I'll submit this to apt repo (I didn't reproduce locally so I'm not sure)

**Comment by strikersix23** [comment]
Still doesnt work its saying group id cannot be added 
https://termbin.com/xuoi

**Comment by strikersix23** [comment]
Here is the exact error
./start.sh
root@localhost:~# apt-get update
Reading package lists... Done
E: Method gave invalid 400 URI Failure message: Failed to set new user ids - setresuid (1: Operation not permitted)
E: Method http has died unexpectedly!
E: Sub-process http returned an error code (112)

**Comment by strikersix23** [comment]
perhaps the setup script is the issue
[ubuntu.txt](https://github.com/termux/proot/files/3510846/ubuntu.txt)

**Comment by strikersix23** [comment]
Yes it was an sh till I uploaded it

**Comment by michalbednarski** [comment]
I've pushed 71573314c1a8e974df1da781752e8815c3148471 to `new_order_void_syscall_fix`, please retest, looks like I was previously wrong about value used as void syscall

**Comment by michalbednarski** [comment]
Updated version is now available in Termux apt repo
