### ISSUE TITLE
Im new and I keep getting this error

### ISSUE THREAD

**Issue by infl4t3d** [termux/proot#72]
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/kali-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.
I'm new to Linux and this kind of stuff

**Comment by infl4t3d** [comment]
This happens when I ./start-kali.sh
The installation said it installed successfully

**Comment by michalbednarski** [comment]
Then it looks like installation didn't actually succeed. Looks like AnLinux install scripts don't fail on error and can print success message on failure (Which could be failed rootfs download (due to network problem or insufficient storage) or proot bug when installation script runs `tar` to extract system)

Anyway, to retry installation (Assuming you've used AnLinux):

```
rm -rf kali-fs
bash kali.sh
```

If still doesn't work post transcript of installation (not just running `./start-kali.sh`, you can save transcript by long pressing in Termux > More... > Share transcript)

**Comment by linuxanakin** [comment]
Happens to me for ubuntu
``./start-ubuntu.sh
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/ubuntu_directory/termux-ubuntu/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`

**Comment by radryry** [comment]
Any fix? I'm having the same issue

**Comment by michalbednarski** [comment]
The situation is still the same, you've shown error indicating that there's a problem with installation of rootfs. You'd need to post messages from system installation which had failed, what you're showing here is attempt to run guest system that is not installed.

**Comment by fgsoftware1** [comment]
> Then it looks like installation didn't actually succeed. Looks like AnLinux install scripts don't fail on error and can print success message on failure (Which could be failed rootfs download (due to network problem or insufficient storage) or proot bug when installation script runs `tar` to extract system)
> 
> Anyway, to retry installation (Assuming you've used AnLinux):
> 
> ```
> rm -rf kali-fs
> bash kali.sh
> ```
> 
> If still doesn't work post transcript of installation (not just running `./start-kali.sh`, you can save transcript by long pressing in Termux > More... > Share transcript)

This works for me

**Comment by Samuelowoode** [comment]
I have installed rootfs

**Comment by Samuelowoode** [comment]
But didn't work

**Comment by skar80** [comment]
I'll try.

**Comment by skar80** [comment]
It didn't work.

**Comment by ROYALKINGSJ** [comment]
> Then it looks like installation didn't actually succeed. Looks like AnLinux install scripts don't fail on error and can print success message on failure (Which could be failed rootfs download (due to network problem or insufficient storage) or proot bug when installation script runs `tar` to extract system)
> 
> Anyway, to retry installation (Assuming you've used AnLinux):
> 
> ```
> rm -rf kali-fs
> bash kali.sh
> ```
> 
> If still doesn't work post transcript of installation (not just running `./start-kali.sh`, you can save transcript by long pressing in Termux > More... > Share transcript)

This worked for mee to and I was using anlinux

**Comment by skar80** [comment]
Thanks for the quick reply and sorry for being late thank you very much

في الجمعة، ٢٠ أيار، ٢٠٢٢ ٩:١٩ ص ROYALKINGSJ ***@***.***> كتب:
