### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by miracle-oss** [termux/proot#73]
I am using a tecno f1 
Android version 8.1.0
I run this command 
./start-parrot.sH
An it showed me
proot info: vpid 1: terminated with signal 11

**Comment by corbinlc** [comment]
@michalbednarski this is an armhf devices running android 8+.  Not a lot of info provided, but maybe related to the signal 11's I was seeing if you could help with.

**Comment by LeapofAzzam** [comment]
Try running this command before running `./start-parrot.sh` or <code>./start-*&lt;distro&gt;*.sh</code> <sup>*¡*</sup>

<sup>¡</sup> *`<distro>`* mean an Linux distro that have you installed in Termux

```bash
unset LD_PRELOAD
export PROOT_NO_SECCOMP=1
hash -r
```
**Note:** `hash -r` is optional

Example:
```bash
$ unset LD_PRELOAD
$ export PROOT_NO_SECCOMP=1
$ hash -r
$ ./start-parrot.sh

**Comment by Grimler91** [comment]
Closing since issue has not been updated in quite a while, please fill in the [bug report template](https://github.com/termux/proot/issues/new?assignees=&labels=&template=bug_report.md) if this is still an issue
