### ISSUE TITLE
Blocker: CANNOT LINK EXECUTABLE "/system/bin/sh"

### ISSUE THREAD

**Issue by zorrobyte** [termux/proot#74]
I'm trying to compile come C modules with termux using proot `termux-chroot`, but some of the compilation steps result in this error:
CANNOT LINK EXECUTABLE "/system/bin/sh": library "/data/data/com.termux/files/usr/lib/libtermux-exec.so" needed or dlopened by "/system/bin/sh" is not accessible for the namespace "(default)"

I'm unsure how to solve it. Any help would be greatly appreciated!

edit: is this due to some sort of permissions issue?
<img width="639" alt="image" src="https://user-images.githubusercontent.com/7257172/65210186-5e983c80-da68-11e9-9fd0-86b2155d6151.png">

This is my printenv
```
termux-chroot
$ printenv
SHELL=/data/data/com.termux/files/usr/bin/bash
PREFIX=/data/data/com.termux/files/usr
PWD=/home
LOGNAME=u0_a128
EXTERNAL_STORAGE=/sdcard
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
HOME=/home
LANG=en_US.UTF-8
TMPDIR=/data/data/com.termux/files/usr/tmp
SSH_CONNECTION=192.168.1.176 50030 192.168.1.158 8022
ANDROID_DATA=/data
TERM=xterm-256color
USER=u0_a128
SHLVL=2
ANDROID_ROOT=/system
SSH_CLIENT=192.168.1.176 50030 8022
PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
SSH_TTY=/dev/pts/1
_=/data/data/com.termux/files/usr/bin/printenv```

**Comment by zorrobyte** [comment]
Setting libtermux-exec.so to 777 permissions fixed it.

**Comment by zorrobyte** [comment]
Trying to set libtermux-exec.so to 777 didn't work.

**Comment by zorrobyte** [comment]
The specific compilation I am attempting is 
```cd /tmp
echo "Installing c-capnp"
git clone https://github.com/commaai/c-capnproto.git
cd c-capnproto
git submodule update --init --recursive
autoreconf -f -i -s
CXXFLAGS="-fPIC" ./configure
make -j4
make install```

**Comment by xeffyr** [comment]
Use `unset LD_PRELOAD`. Termux-exec lib shouldn't be used inside proot.
