### ISSUE TITLE
Cannot hard link/sym link to ... : Permission denied

### ISSUE THREAD

**Issue by Zom101** [termux/proot#75]
I have an armhf device that recently got updated to android 9.0. After this update it seems impossible to run linux under proot.

Here is what the situation looks like:
![Screenshot_20190915-103054](https://user-images.githubusercontent.com/55152960/65222365-95516f80-dac7-11e9-9126-f20f59e81c5d.png)

I tried many apps and ways but the same things are happening.

**Comment by michalbednarski** [comment]
What install script do you use?

Please run following command and share results
```
PROOT_VERBOSE=9 YOUR_INSTALL_SCRIPT |& busybox nc termbin.com 9999
```

(Replace `YOUR_INSTALL_SCRIPT` with command you've used in first place)

**Comment by Zom101** [comment]
If I do that, it just stops halfway through the download.

https://termbin.com/jg4i

I used the script from AnLinux.

**Comment by corbinlc** [comment]
@michalbednarski, I sent @zom101 here after he tried using proot in termux.  This is related to CypherpunkArmory/UserLAnd#1046 and #71 here.

**Comment by Zom101** [comment]
Here is the log: 
[log.txt](https://github.com/termux/proot/files/3632800/log.txt)

**Comment by corbinlc** [comment]
Thought... since this is only showing up on devices getting updates to newer version of Android, could it be related to the devices going from kernel <= 4.7 to kernel > 4.7.  This would change how `PTRACE_EVENT_SECCOMP` behaves.  Maybe there is something specific to that change + `armhf` that proot is not handling well.

**Comment by Zom101** [comment]
Alpine from AnLinux seems to be working, but it's kind of useless:

![Screenshot_20190922-110028](https://user-images.githubusercontent.com/55152960/65384259-d4323000-dd28-11e9-801d-303961bd2d4e.png)

**Comment by michalbednarski** [comment]
I've pushed experimental fix to `arm-seccomp-skips-sysexit` branch.

Tested on Raspbian (with seccomp filters dumped from Android) in QEMU, with basic test of

```
proot -v 9 cat /nosuchdir/something /etc/passwd
```

(After fix I can see `translate("/" + "/etc/passwd")` in trace)

**Comment by Zom101** [comment]
How can i test that?

**Comment by michalbednarski** [comment]
```
pkg install -y git clang make libtalloc
git clone https://github.com/termux/proot -b arm-seccomp-skips-sysexit
cd proot/src
make
make install
```

**Comment by Zom101** [comment]
It gives the same errors.

Log: 
[log.txt](https://github.com/termux/proot/files/3639740/log.txt)

**Comment by Zom101** [comment]
Any idea why that version of alpine works? Maybe because it's a really basic version?

> Alpine from AnLinux seems to be working, but it's kind of useless:
> 
> ![Screenshot_20190922-110028](https://user-images.githubusercontent.com/55152960/65384259-d4323000-dd28-11e9-801d-303961bd2d4e.png)

**Comment by michalbednarski** [comment]
> Any idea why that version of alpine works? Maybe because it's a really basic version?

Looks like `busybox ash`, unlike `bash` in other distros doesn't use `getpgrp(2)` which is not in bionic syscall whitelist. However `apk add` uses `symlink(2)` which isn't whitelisted so you won't get far.

---

Regarding my proot build instructions I've noticed that `apt` will consume stdin so executing all commands in single paste won't work. Upon successful build last lines should be

```
$ make install
  INSTALL       proot
$
```

---

If after build from repository still doesn't work, I'd ask for full strace of proot

```
strace -o trace.txt -vs50000 proot -v 9 --link2symlink -0 -r ubuntu-fs -b /dev -b /proc -b ubuntu-fs/root:/dev/shm -w /root /usr/bin/env -i HOME=/root PATH=/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/games:/usr/local/games TERM=screen-256color LANG=C.UTF-8 /bin/bash --login
```

**Comment by Zom101** [comment]
Ok, i did it properly and still doesn't work. Is it ok to use strace after the installation failed?

[trace.txt](https://github.com/termux/proot/files/3667909/trace.txt)

**Comment by michalbednarski** [comment]
I've reviewed trace.txt and I'm pretty sure that while this proot version was built on device, it didn't contain fix

This can be checked with 
```
$ strings $(which proot) | grep 'already handled sysenter'
skipping PTRACE_EVENT_SECCOMP for already handled sysenter
```
(If running on fixed version string should be present, as it was added in a4510a6465edb9631a3e6a5d232f06532c013842)

Possibly you hadn't checked correct branch (`-b` option during `git clone` in above instruction), checkout it with:
```
git fetch
git checkout origin/arm-seccomp-skips-sysexit
```

**Comment by Zom101** [comment]
Now it cannot install packages

![Screenshot_20191001-201303](https://user-images.githubusercontent.com/55152960/65984249-03af0e00-e488-11e9-99b0-49e6df0e0b01.png)

I just copied and pasted from your instruction, i am pretty sure i did not missed the -b option, but i will try again when it will let me.

**Comment by oxr463** [comment]
That message has nothing to do with PRoot. That just means there is a problem with the package repository.

**Comment by Zom101** [comment]
I think i was installing again proot without fix... Sorry for wasting your time like that.

Now it gives a signal 6 error: 
[log.txt](https://github.com/termux/proot/files/3678281/log.txt)

**Comment by michalbednarski** [comment]
I'd ask for rootfs extraction strace then (using version with fix)

```
wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Rootfs/Ubuntu/armhf/ubuntu-rootfs-armhf.tar.xz -O ubuntu-rootfs.tar.xz
strace -o trace.txt -vs50000 proot -v 9 --link2symlink tar -xJf /data/data/com.termux/files/home/ubuntu-rootfs.tar.xz
```

**Comment by Zom101** [comment]
Forgot to output to a file, i hope that's not a problem

[Terminal transcript.txt].(https://github.com/termux/proot/files/3680620/Terminal.transcript.txt)

**Comment by michalbednarski** [comment]
I'd need `trace.txt` outputted by `strace`

**Comment by Zom101** [comment]
[trace.txt](https://github.com/termux/proot/files/3680710/trace.txt)

**Comment by michalbednarski** [comment]
I've pushed 08e67dda1b2bac5b34d4ae7d8c460a8da9f32457 to fix second bug, please re-test (`git pull` or re-clone from same branch).

You can check if built version is one with fix using `strings`, fixed version will have both listed
```
$ strings $(which proot) | grep 'already handled sysenter'
skipping SIGTRAP for already handled sysenter
skipping PTRACE_EVENT_SECCOMP for already handled sysenter
```

**Comment by Zom101** [comment]
[trace1.txt](https://github.com/termux/proot/files/3685852/trace1.txt)

**Comment by michalbednarski** [comment]
Looks like `tar` during installation doesn't crash anymore, try running full distro

**Comment by Zom101** [comment]
It seems to be running, but it doesn't allow you to do much:
[Terminal transcript1.txt](https://github.com/termux/proot/files/3685932/Terminal.transcript1.txt)

**Comment by michalbednarski** [comment]
I'd need strace again:

```
unset LD_PRELOAD
echo 'apt update ; apt list' | strace -vs50000 proot -v 9 --link2symlink -0 -r ubuntu-fs -b /dev -b /proc -b ubuntu-fs/root:/dev/shm -w /root /usr/bin/env -i HOME=/root PATH=/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/games:/usr/local/games TERM=screen-256color LANG=C.UTF-8 /bin/bash --login >& trace.txt
```

**Comment by Zom101** [comment]
[trace2.txt](https://github.com/termux/proot/files/3691486/trace2.txt)

**Comment by michalbednarski** [comment]
Just pushed fix, please re-test distro and if still doesn't work then I'd need strace again (but hopefully it should be working now)

**Comment by Zom101** [comment]
Ok it worked, but there is still one more issue (i think it's the only one left) when installing certain apps, like this one:

[trace 3.txt](https://github.com/termux/proot/files/3693465/trace.3.txt)

**Comment by michalbednarski** [comment]
Fix pushed, please re-test

**Comment by Zom101** [comment]
Everything seems to be working now, i guess it's done.
