### ISSUE TITLE
AArch32 support

### ISSUE THREAD

**Issue by yuxue521** [termux/proot#77]
I am using a 64 bit android system I want to simulate armhf debian but can't run

proot info: vpid 1: terminated with signal 11

**Comment by michalbednarski** [comment]
Running 32-bit arm on 64 bit host is not yet supported, I'll look into that in following week.

**Comment by michalbednarski** [comment]
Implementation is now available for testing on `arm-seccomp-skips-sysexit` branch, I think it'll be released to apt repo in next week if everything goes well

**Comment by corbinlc** [comment]
@michalbednarski  I think this change broke building the unbundled loader.  Specifically, I think using `-m32` in the `GNUmakefile` doesn't work when building `loader-m32` for arm.

```
aarch64-linux-android-clang -m32 -o loader/loader-m32 loader/loader-m32.o loader/assembly-m32.o -static -nostdlib -Wl,--build-id=none,-Ttext=0x10000000,-z,noexecstack
/usr/bin/ld: unrecognised emulation mode: armelf_linux_eabi
Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 elf_iamcu i386linux elf_l1om elf_k1om i386pep i386pe
```

Why is the `-m32` used at all?  I know it is for x86, but I am not sure why the `loader-m32` cannot match the architecture of the device it is running on.  Specifically, when the loader is self extracted, and not bundled, it appears to not be compiled and linked with any additional flags.

**Comment by corbinlc** [comment]
I guess this issue should happen when it is unbundled or bundled.  It is odd that you haven't seen it, as `-m32` doesn't look like it is supported for aarch64 in general.  I wonder if your version of clang is ignoring it, or replacing it with a different set of options.  Any thoughts?

**Comment by yuxue521** [comment]
@michalbednarski Thank you very much, I have successfully run debian armhf on 64 bit host

**Comment by michalbednarski** [comment]
Looks like you've already figured out, but for the record:

`aarch64-linux-android-clang -m32` works like `arm-linux-androideabi-clang` (At least with `-static -nostdlib`)

```
$ wget https://api.cirrus-ci.com/v1/artifact/task/6242846805327872/output/debs/proot_5.1.107-23_aarch64.deb
[...]
$ dpkg --extract proot_5.1.107-23_aarch64.deb proot-aarch64     
$ cd proot-aarch64/data/data/com.termux/files/usr/libexec/proot/
$ file *
loader:   ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, stripped
loader32: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, stripped
```

Proot package normally builds; CI for termux-packages built `deb`s (https://github.com/termux/termux-packages/pull/4393/checks). These changes are merged into `termux-packages` GitHub repo and while they are not available via apt yet they should be soon.
