### ISSUE TITLE
filter xattrs?

### ISSUE THREAD

**Issue by tomty89** [termux/proot#8]
Is it possible for proot to filter extended attributes (xattrs)?

```
[root@localhost ~]# mkdir test
[root@localhost ~]# cd test/
[root@localhost test]# touch hey
[root@localhost test]# getfattr -n security.selinux hey
# file: hey
security.selinux="u:object_r:app_data_file:s0:c512,c768"

[root@localhost test]# setfattr -n security.selinux hey
setfattr: hey: Permission denied
[root@localhost test]# getfattr -n test hey
hey: test: Operation not supported
[root@localhost test]# setfattr -n test hey
setfattr: hey: Operation not supported
```
This for example causes trouble to `shutil.copystat()` in python3 (https://github.com/sdrausty/TermuxArch/issues/30#issuecomment-362197469) and GNU patch:
```
[root@localhost test]# echo hi > hi
[root@localhost test]# echo hello > hello
[root@localhost test]# git diff hi hello > test.patch
[root@localhost test]# patch -i test.patch hi
patching file hi
patch: setting attribute security.selinux for security.selinux: Permission denied
```
which I currently work around by rebuilding it with `--disable-xattr`.

**Comment by michalbednarski** [comment]
I'll look into it

**Comment by michalbednarski** [comment]
Fixed version is now available in apt repo, run `pkg up` to update

**Comment by tomty89** [comment]
Works perfectly, thanks!

**Comment by arkanoid87** [comment]
this is back

patch: setting attribute security.selinux for security.selinux:

```
-bash-4.4$ proot --version
 _____ _____              ___
|  __ \  __ \_____  _____|   |_
|   __/     /  _  \/  _  \    _|
|__|  |__|__\_____/\_____/\____| 5.1.0

built-in accelerators: process_vm = no, seccomp_filter = yes

Visit http://proot.me for help, bug reports, suggestions, patchs, ...
Copyright (C) 2015 STMicroelectronics, licensed under GPL v2 or later.
-bash-4.4$
```

**Comment by michalbednarski** [comment]
This functionality is part of fake_id0, please check that `id` reports that
you're root.

If fake_id0 is active please provide system information and detailed log:

script
uname -a
dpkg --print-architecture
cat /proc/$$/status
PROOT_VERBOSE=9 ./your-proot-wrapper.sh

(Replace ./your-proot-wrapper.sh with command you use to start prooted
environment, script records terminal transcript to file called typescript,
finish terminal recording with Ctrl-D)

**Comment by arkanoid87** [comment]
I did not know that the filter was active on just id0, now it works if I use use id 0. Thank you.

I am trying to compile Gentoo Prefix inside Archlinux (startarch) proot environment.

**Comment by imShara** [comment]
Same here. Trying to compile openwrt under archlinux in proot under non-root user and get same error

**Comment by imShara** [comment]
@xeffyr but if you will build under root (id0), you should set FORCE_UNSAFE_CONFIGURE=1 flag

**Comment by xd003** [comment]
I am facing this same issue , can someone help me please
```
​[tester@localhost fakeroot-tcp]$ makepkg
==> Making package: fakeroot-tcp 1.24-2 (Fri Sep  4 06:27:47 2020)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found fakeroot_1.24.orig.tar.gz
  -> Found silence-dlerror.patch
==> Validating source files with md5sums...
    fakeroot_1.24.orig.tar.gz ... Passed
    silence-dlerror.patch ... Passed
==> Extracting sources...
  -> Extracting fakeroot_1.24.orig.tar.gz with bsdtar
==> Starting prepare()...
patching file libfakeroot.c
patch: setting attribute security.selinux for security.selinux: Permission denied
==> ERROR: A failure occurred in prepare().
    Aborting...
```

I read above that we need to run the command as a root user but makepkg doesn't even works in sudo
```
[root@localhost fakeroot-tcp]# makepkg -di
==> ERROR: Running makepkg as root is not allowed as it can cause permanent,
catastrophic damage to your system.
```

How do i fix it

**Comment by xd003** [comment]
> @xeffyr but if you will build under root (id0), you should set FORCE_UNSAFE_CONFIGURE=1 flag

Doesn't seem to work for me
While being logged in as root user i did
```export FORCE_UNSAFE_CONFIGURE=1```

But it still returns the same error that we cannot run makepkg as root
```
[root@localhost fakeroot-tcp]# makepkg -di
==> ERROR: Running makepkg as root is not allowed as it can cause permanent,
catastrophic damage to your system.
```

**Comment by xd003** [comment]
> I am facing this same issue , can someone help me please
> 
> ```
> ​[tester@localhost fakeroot-tcp]$ makepkg
> ==> Making package: fakeroot-tcp 1.24-2 (Fri Sep  4 06:27:47 2020)
> ==> Checking runtime dependencies...
> ==> Checking buildtime dependencies...
> ==> Retrieving sources...
>   -> Found fakeroot_1.24.orig.tar.gz
>   -> Found silence-dlerror.patch
> ==> Validating source files with md5sums...
>     fakeroot_1.24.orig.tar.gz ... Passed
>     silence-dlerror.patch ... Passed
> ==> Extracting sources...
>   -> Extracting fakeroot_1.24.orig.tar.gz with bsdtar
> ==> Starting prepare()...
> patching file libfakeroot.c
> patch: setting attribute security.selinux for security.selinux: Permission denied
> ==> ERROR: A failure occurred in prepare().
>     Aborting...
> ```
> 
> I read above that we need to run the command as a root user but makepkg doesn't even works when logged in as root user
> 
> ```
> [root@localhost fakeroot-tcp]# makepkg -di
> ==> ERROR: Running makepkg as root is not allowed as it can cause permanent,
> catastrophic damage to your system.
> ```
> 
> How do i fix it

@xeffyr @michalbednarski 
Is there any way around this issue , makepkg doesn't works as root user and non root user just returns the error - ```patch: setting attribute security.selinux for security.selinux```

**Comment by xeffyr** [comment]
@xd003 You need to bootstrap the fakeroot-tcp:

1. Compile and install the fakeroot manually (without makepkg) with prefix=/usr/local and with TCP IPC.
2. Ensure that no fakeroot oackages are installed.
3. Build fakeroot-tcp with makepkg.

You have no other way since only fakeroot can absorb xattrs with no permission denials.
