### ISSUE TITLE
can't mount /dev/shm

### ISSUE THREAD

**Issue by seisdr** [termux/proot#83]
I get this  while launching enlightenment 
```
currently unimplemented ecore_x_image_get without shm
```
I tried this 
```
root@localhost:~# mkdir /dev/shm && mount -t shm tmpfs /dev/shm
mount: /dev/shm: cannot mount tmpfs read-only.
```
proot has --mount option that gonna help?

**Comment by oxr463** [comment]
Can you provide the command used for executing PRoot?

**Comment by seisdr** [comment]
.

**Comment by michalbednarski** [comment]
In general, you cannot use mount inside proot, you'd have to specify mounts in proot command line.

Easiest way to do so is adding following to launcher script ([taken from here](https://github.com/MFDGaming/ubuntu-in-termux/blob/042f0ffa3f345e897610c8ad89c7756a079caedf/ubuntu.sh#L80))
```
command+=" -b ubuntu-fs/tmp:/dev/shm"
```

(`/dev/shm` should be some writable directory, reusing same directory as guest `/tmp` appears to be ok)

**Comment by seisdr** [comment]
Still
```
currently unimplemented ecore_x_image_get without shm
currently unimplemented ecore_x_image_get without shm
currently unimplemented ecore_x_image_get without shm
currently unimplemented ecore_x_image_get without shm
currently unimplemented ecore_x_image_get without shm
currently unimplemented ecore_x_image_get without shm
currently unimplemented ecore_x_image_get without shm
currently unimplemented ecore_x_image_get without shm
currently unimplemented ecore_x_image_get without shm
currently unimplemented ecore_x_image_get without shm
```

**Comment by michalbednarski** [comment]
I've found that this error is not about `/dev/shm`, but about [MIT-SHM X server extension](https://en.wikipedia.org/wiki/MIT-SHM)

Looks like Enlightenment can run without that if you uncheck `Enable Compositing` during initial Enlightenment setup (Do `rm -rf ~/.e` to wipe Enlightenment settings and start over)

MIT-SHM is based on SysV Shared Memory which is unsupported on Android and as Xserver usually runs outside proot support would require changes to both proot and Xserver being used

**Comment by seisdr** [comment]
oh wow thanks I can't open programs but it launched!
