### ISSUE TITLE
Change TCSAFLUSH flag to TCSANOW due to new restrictions

### ISSUE THREAD

**Issue by Hax4us** [termux/proot#88]
This issue https://github.com/termux/termux-packages/issues/1359 was solved inside termux but still happening in prooted environment
According to @xeffyr 
Since TCSAFLUSH is set via

`ioctl(fd, TCSETS+TCSAFLUSH /* values: 0x5402+2 */, &term)`
it should be possible to modify proot to replace ioctl arguments to something like:

`ioctl(fd, TCSETS+TCSANOW /* values: 0x5402+0 */, &term)`

**Comment by michalbednarski** [comment]
Fixed, updated version is now available in Termux apt repo
