### ISSUE TITLE
Add shared memory support to Proot

### ISSUE THREAD

**Issue by JanuszChmiel** [termux/proot#89]
May be, that this issue have been created previously. What do you think about adding shared memory support directly to Proot? Currently there is no easy technique, which would allow Termux Proot users to add this shared memory supported to various Linux distributions, which are being executed by Proot.
Namely, the following could be implemented to work.
(shmget, shmat, shmdt and shmctl) 
Original library for Termux which solves this is available here:

https://github.com/termux/libandroid-shmem
Sure, I Am ready to intensively test and if working on my phone remotely will be required, no problem, I will ive you access by using tmate SSH client.
What do you think. Would be too complex to achieve this goal? If it would be too complex to create it for many Linux distributions, would be possible to create this support for Debian Buster ARM 64 Bit?
Thank you very much for yours analysis and for yours thinkink about my plea.

**Comment by ZhymabekRoman** [comment]
Hello, @JanuszChmiel !
Now proot supports shm, you can use now.

**Comment by JanuszChmiel** [comment]
Thank you very much for yours complex programmers work. It had to be difficult. Do you think, that thanks to yours Proot extension to support shared memory, Pcmanfm and GTK3 library will finally stop do display warning shmget function not implemented?

Thanks to yours Proot extension, it is next very important Linux distribution support miracle. Because there are some Linux apps which really dependent on shared memory support. I will test it on some simple Linux distribution install script, where /dev/shm is not created to avoid some conflicts between various shared memory support approaches. Very well done and thank you, that you have used yours perfect programmers knowledge.

**Comment by JanuszChmiel** [comment]
Here is The command result.

[root20:36sbin]$ um
x86_64
BUt ping binary do not exist on The installation. SO I do not know how 
to test if Internet functioning or no.

When i Execute
[root20:38sbin]$ pacman -Syu
:: Synchronizing package databases...
error: failed to update core (no servers configured for repository)
error: failed to update extra (no servers configured for repository)
error: failed to update community (no servers configured for repository)
error: failed to synchronize all databases
[root20:38sbin]$
It seems to Me, that there is some hydden problem. That there is complex 
way to go to configure foreign architecture so professionally like yours 
script allready do for normal situation when user install Archlinux and 
Proot is being used for Qemu.
The complex issue is to find links for repositories and how to digitally 
sign some keys. But I will be patiently testing and I AM looking forward 
to The times, when
pacman SYu
will update whole distro and I will be even able to install Orca and 
Mate when using ArchLinux by using Qemu and Proot.


-- 
Tento e-mail byl zkontrolován na viry programem AVG.
http://www.avg.cz

**Comment by xeffyr** [comment]
> error: failed to update core (no servers configured for repository)

Then configure a mirror. It is not being set.

Look for files /etc/pacman.conf and /etc/pacman.d/mirrorlist.
