### ISSUE TITLE
New proot causes problems for Fedora under termux on all Android machines I own.

### ISSUE THREAD

**Issue by srdegraaf** [termux/proot#9]
I'm trying to use Milosevic's Fedora (26, arm) under termux script (https://github.com/nmilosev/termux-fedora/blob/master/termux-fedora.sh). It no longer works.

As of proot-5.1.106-5 (via a toxic apt update) this no longer works under either Android 6.0.1 (Motorola Droid Turbo phone) or LineageOS 14.1 (Samsung Galaxy Tab Pro 8.4"). I am using termux 0.60 from the Android Play Store. I've been using termux for a couple years, i.e. with earlier and current versions as well as from F-Droid - running Fedora 25 and 26 (27's dnf is terminally diseased on arm courtesy of some kind of Python but) via proot - with no problems on both devices. Now it won't work. I miss it! Please see below for diagnostics.

In the interim before a fix, how can I make termux downgrade to an earlier version of proot? (On Fedora, it's easy: dnf downgrade packagexyz. On debian/termux I can't seem to figure it out.)

$ startfedora
proot error: execve("/usr/bin/env"): No such file or directory
proot info: possible causes:

    the program is a script but its interpreter (eg. /bin/sh) was not found;
    the program is an ELF but its interpreter (eg. ld-linux.so) was not found;
    the program is a foreign binary but qemu was not specified;
    qemu does not work correctly (if specified);
    the loader was not found or doesn't work.
    fatal error: see proot --help.
    proot error: can't chmod '/data/data/com.termux/files/usr/tmp//proot-2076-GQJIxt': No such file or directory
    proot error: can't chdir to ' ': No such file or directory

Any ideas how to fix this?

Thanks! I love termux!

Stuart DeGraaf

**Comment by michalbednarski** [comment]
For diagnosis I'd probably need to see
```sh
uname -a
PROOT_VERBOSE=9 startfedora 2>log.txt
```

Termux doesn't keep old packages in it's [apt repo](http://termux.net/), so standard Debian downgrade method won't work, instead you'll need older .deb (Prebuilt by me just now: [proot_5.1.106-4_arm.deb.zip](https://github.com/termux/proot/files/1728929/proot_5.1.106-4_arm.deb.zip))

Install it with
```sh
apt install ./proot_5.1.106-4_arm.deb
```
(Note that next `apt upgrade` will upgrade it again)

Above .deb was built by running following commands in Vagrant VM from termux-packages repo:
```sh
cd /termux-packages
git checkout fc9175b05b019d7d74080b378c2df4355cb800ea
./build-package.sh -a arm proot
```

**Comment by Neo-Oli** [comment]
I had this error in both my [termux-ubuntu](https://github.com/Neo-Oli/termux-ubuntu) and [chrooted-termux](https://github.com/Neo-Oli/chrooted-termux) scripts, which are both very similar (and inspired by) termux-fedora. I think the problem is the LD_PRELOAD variable. Since recently [termux-exec](https://wiki.termux.com/wiki/Termux-exec) is installed by default. It's a piece of code that gets executed before every command. Since it isn't installed inside the fedora jail (at the correct path /data/data/com.termux...) proot throws an error. @nmilosev can fix this by running `unset LD_PRELOAD` inside the launch script for fedora.

Can you verify for me if it works if you run `unset $LD_PRELOAD` before you run startfedora?

**Comment by srdegraaf** [comment]
Neo-Oli - your solution did the trick! Thanks very much!
michalbednarski - the older version of proot didn't help (I sent you the error info). Neo-Oli's solution works with both new and old proots.

**Comment by michalbednarski** [comment]
I've added warning about termux-exec to proot when it's active and first executable was not found

I think that's all that can be done on proot side

**Comment by Helms-Deep** [comment]
@Neo-Oli, Hi,
Although this is an old post, just wanted to thank you. Can't imagine without Termux. You are a lifesaver and a damn genius. Thanks a mil!

**Comment by tathastu871** [comment]
> I had this error in both my [termux-ubuntu](https://github.com/Neo-Oli/termux-ubuntu) and [chrooted-termux](https://github.com/Neo-Oli/chrooted-termux) scripts, which are both very similar (and inspired by) termux-fedora. I think the problem is the LD_PRELOAD variable. Since recently [termux-exec](https://wiki.termux.com/wiki/Termux-exec) is installed by default. It's a piece of code that gets executed before every command. Since it isn't installed inside the fedora jail (at the correct path /data/data/com.termux...) proot throws an error. @nmilosev can fix this by running `unset LD_PRELOAD` inside the launch script for fedora.
> 
> Can you verify for me if it works if you run `unset $LD_PRELOAD` before you run startfedora?

it did not worked. same error again and again on fedora and ubuntu and all other prooted os

**Comment by michalbednarski** [comment]
`unset $LD_PRELOAD` was typo, it should be `unset LD_PRELOAD` (without `$`)

It doesn't really make sense to comment on old closed issues here, similar errors can have different root causes and if issue is closed it probably isn't directly related to your error.

If you still have problem please open new issue, but be sure to include what results you've exactly got, what you've used to install distro, `uname -a`, `dpkg --print-architecture` and be ready to follow up with logs.

**Comment by xeffyr** [comment]
Typo in https://github.com/termux/proot/issues/9#issuecomment-366035231 is now fixed.
