### ISSUE TITLE
Warning: ptrace(POKEDATA): I/O error in termux-ubuntu

### ISSUE THREAD

**Issue by ferfebles** [termux/proot#96]
From https://github.com/proot-me/proot/issues/213#issue-564813304
----------------------------------
## Expected Behavior
Press TAB key inside shell and show the completion list files and folders

## Actual Behavior
Press TAB and a warning is shown

## Steps to Reproduce the Problem

  1. Install Termux in an android device
  2. Install Ubuntu inside termux
  3. Launch ubuntu and press TAB key

## Specifications

  - Proot/Care version: 5.1.0
  - Kernel version: Android 8.1.0, kernel 3.18.14
  - Host distribution: Samsung
  - Guest distribution: Termux - Ubuntu LTS

## Command Output

```terminal
root@localhost:~/test# ls
proot info: vpid 11: pid 2367
proot info: vpid 11: translate("/" + "/bin/ls")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/usr/bin/ls"
proot info: vpid 11: translate("/" + "/lib/ld-linux-armhf.so.3")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/usr/lib/arm-linux-gnueabihf/ld-2.29.so"
proot info: vpid 11: translate("/" + "/bin/ls")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/usr/bin/ls"
proot info: vpid 11: translate("/" + "/lib/ld-linux-armhf.so.3")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/usr/lib/arm-linux-gnueabihf/ld-2.29.so"
proot info: vpid 11: translate("/" + "/etc/ld.so.preload")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/etc/ld.so.preload"
proot info: vpid 11: translate("/" + "/etc/ld.so.cache")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/etc/ld.so.cache"
proot info: vpid 11: translate("/" + "/lib/arm-linux-gnueabihf/libselinux.so.1")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/usr/lib/arm-linux-gnueabihf/libselinux.so.1"
proot info: vpid 11: translate("/" + "/lib/arm-linux-gnueabihf/libc.so.6")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/usr/lib/arm-linux-gnueabihf/libc-2.29.so"
proot info: vpid 11: translate("/" + "/lib/arm-linux-gnueabihf/libpcre.so.3")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/usr/lib/arm-linux-gnueabihf/libpcre.so.3.13.3"
proot info: vpid 11: translate("/" + "/lib/arm-linux-gnueabihf/libdl.so.2")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/usr/lib/arm-linux-gnueabihf/libdl-2.29.so"
proot info: vpid 11: translate("/" + "/lib/arm-linux-gnueabihf/libpthread.so.0")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/usr/lib/arm-linux-gnueabihf/libpthread-2.29.so"
proot info: vpid 11: translate("/" + "/sys/fs/selinux")
proot info: vpid 11: translate("/" + "/dev/shm")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/tmp"
proot info: vpid 11: translate("/" + "/selinux")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/selinux"
proot info: vpid 11: translate("/" + "/proc/filesystems")                                                                                         proot info: vpid 11:          -> "/proc/filesystems"
proot info: vpid 11: translate("/" + "/proc/mounts")
proot info: vpid 11:          -> "/proc/2367/mounts"
proot info: vpid 11: translate("/" + "/sys/fs/selinux")
proot info: vpid 11: translate("/" + "/dev/shm")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/tmp"
proot info: vpid 11: translate("/" + "/etc/selinux/config")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/etc/selinux/config"
proot info: vpid 11: translate("/" + "/usr/lib/locale/locale-archive")                                                                            proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/usr/lib/locale/locale-archive"
proot info: vpid 11: translate("/" + "/usr/share/locale/locale.alias")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/etc/locale.alias"
proot info: vpid 11: translate("/" + "/usr/lib/locale/C.UTF-8/LC_IDENTIFICATION")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/usr/lib/locale/C.UTF-8/LC_IDENTIFICATION"
proot info: vpid 11: translate("/" + "/usr/lib/arm-linux-gnueabihf/gconv/gconv-modules.cache")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/usr/lib/arm-linux-gnueabihf/gconv/gconv-modules.cache"
proot info: vpid 11: translate("/" + "/usr/lib/locale/C.UTF-8/LC_MEASUREMENT")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/usr/lib/locale/C.UTF-8/LC_MEASUREMENT"
proot info: vpid 11: translate("/" + "/usr/lib/locale/C.UTF-8/LC_TELEPHONE")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/usr/lib/locale/C.UTF-8/LC_TELEPHONE"
proot info: vpid 11: translate("/" + "/usr/lib/locale/C.UTF-8/LC_ADDRESS")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/usr/lib/locale/C.UTF-8/LC_ADDRESS"
proot info: vpid 11: translate("/" + "/usr/lib/locale/C.UTF-8/LC_NAME")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/usr/lib/locale/C.UTF-8/LC_NAME"
proot info: vpid 11: translate("/" + "/usr/lib/locale/C.UTF-8/LC_PAPER")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/usr/lib/locale/C.UTF-8/LC_PAPER"
proot info: vpid 11: translate("/" + "/usr/lib/locale/C.UTF-8/LC_MESSAGES")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/usr/lib/locale/C.UTF-8/LC_MESSAGES"
proot info: vpid 11: translate("/" + "/usr/lib/locale/C.UTF-8/LC_MESSAGES/SYS_LC_MESSAGES")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/usr/lib/locale/C.UTF-8/LC_MESSAGES/SYS_LC_MESSAGES"
proot info: vpid 11: translate("/" + "/usr/lib/locale/C.UTF-8/LC_MONETARY")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/usr/lib/locale/C.UTF-8/LC_MONETARY"
proot info: vpid 11: translate("/" + "/usr/lib/locale/C.UTF-8/LC_COLLATE")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/usr/lib/locale/C.UTF-8/LC_COLLATE"
proot info: vpid 11: translate("/" + "/usr/lib/locale/C.UTF-8/LC_TIME")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/usr/lib/locale/C.UTF-8/LC_TIME"
proot info: vpid 11: translate("/" + "/usr/lib/locale/C.UTF-8/LC_NUMERIC")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/usr/lib/locale/C.UTF-8/LC_NUMERIC"
proot info: vpid 11: translate("/" + "/usr/lib/locale/C.UTF-8/LC_NUMERIC")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/usr/lib/locale/C.UTF-8/LC_NUMERIC"
proot info: vpid 11: translate("/" + "/usr/lib/locale/C.UTF-8/LC_CTYPE")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/usr/lib/locale/C.UTF-8/LC_CTYPE"
proot info: vpid 11: translate("/root/test" + ".")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/root/test/."
proot info: vpid 11: translate("/root/test" + "dir_one")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/root/test/dir_one"
proot info: vpid 11: translate("/root/test" + "dir_two")
proot info: vpid 11:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/root/test/dir_two"
dir_one  dir_two
proot info: vpid 11: exited with status 0
root@localhost:~/test#
root@localhost:~/test#
root@localhost:~/test#
root@localhost:~/test# cd dir_proot info: vpid 1: translate("/" + "/dev/null")
proot info: vpid 1:          -> "/dev/null"                                                                                                       proot info: vpid 1: translate("/" + "/dev/null")
proot info: vpid 1:          -> "/dev/null"
proot info: vpid 12: pid 2369
proot info: vpid 12: translate("/root/test" + ".")
proot info: vpid 12:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/root/test/."
proot info: vpid 12: translate("/root/test" + "dir_one")
proot info: vpid 12:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/root/test/dir_one"
proot info: vpid 12: translate("/root/test" + "dir_two")
proot info: vpid 12:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/root/test/dir_two"
proot info: vpid 12: exited with status 0
proot info: vpid 1: translate("/" + "/tmp")
proot info: vpid 1:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/tmp"
proot info: vpid 1: translate("/" + "/tmp")
proot info: vpid 1:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/tmp"
proot info: vpid 1: translate("/" + "/tmp")
proot info: vpid 1:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/tmp"
proot info: vpid 1: translate("/" + "/dev/shm")
proot info: vpid 1:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/tmp"
proot warning: ptrace(POKEDATA): I/O error
proot info: vpid 1: translate("/" + "/tmp/sh-thd.G6d74f")
proot info: vpid 1:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/tmp/sh-thd.G6d74f"
proot info: vpid 1: translate("/" + "/tmp/sh-thd.G6d74f")
proot info: vpid 1:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/tmp/sh-thd.G6d74f"
proot info: vpid 1: translate("/" + "/tmp/sh-thd.G6d74f")
proot info: vpid 1:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/tmp/sh-thd.G6d74f"
proot info: vpid 1: translate("/" + "/dev/null")
proot info: vpid 1:          -> "/dev/null"
```

**Comment by michalbednarski** [comment]
1. Please capture output with higher proot verbosity level (`PROOT_VERBOSE=9` or `-v 9`)
2. What did you use to install Ubuntu inside Termux? (Installation script or manual rootfs download and proot launch command)

**Comment by ferfebles** [comment]
I´v used the installation script

**Comment by ferfebles** [comment]
Capture with -v 9

------------------------------------------------------------
root@localhost:~/test# cd dir_proot info: vpid 1: sysenter start: openat(0xffffff9c, 0xf19c720, 0x20241, 0x1b6, 0xebe6a000, 0x1f028930) = 0xffffff9c [0xffcffce8, 0]
proot info: vpid 1: translate("/" + "/dev/null")
proot info: vpid 1:          -> "/dev/null"
proot info: vpid 1: sysenter end: openat(0xffffff9c, 0xffcffcde, 0x20241, 0x1b6, 0xebe6a000, 0x1f028930) = 0xffffff9c [0xffcffce8, 0]
proot info: vpid 1: sysenter start: fstat64(0x1, 0xffcff700, 0xffcff700, 0xebdc7be5, 0xebe6adb8, 0xebe6b374) = 0x1 [0xffcff6f4, 0]
proot info: vpid 1: sysenter end: fstat64(0x1, 0xffcff700, 0xffcff700, 0xebdc7be5, 0xebe6adb8, 0xebe6b374) = 0x1 [0xffcff6f4, 0]
proot info: vpid 1: sysexit start: fstat64(0x0, 0xffcff700, 0xffcff700, 0xebdc7be5, 0xebe6adb8, 0xebe6b374) = 0x0 [0xffcff6f4, 0]
proot info: vpid 1: sysexit end: fstat64(0x0, 0xffcff700, 0xffcff700, 0xebdc7be5, 0xebe6adb8, 0xebe6b374) = 0x0 [0xffcff6f4, 0]
proot info: vpid 1: sysenter start: ioctl(0x1, 0x5401, 0xffcff678, 0xffcff6b8, 0xad6ffa00, 0x158) = 0x1 [0xffcff670, 0]
proot info: vpid 1: sysenter end: ioctl(0x1, 0x5401, 0xffcff678, 0xffcff6b8, 0xad6ffa00, 0x158) = 0x1 [0xffcff670, 0]
proot info: vpid 1: sysenter start: openat(0xffffff9c, 0xf19b418, 0x20241, 0x1b6, 0xebe6a000, 0x1f028930) = 0xffffff9c [0xffd00558, 0]
proot info: vpid 1: translate("/" + "/dev/null")
proot info: vpid 1:          -> "/dev/null"
proot info: vpid 1: sysenter end: openat(0xffffff9c, 0xffd0054e, 0x20241, 0x1b6, 0xebe6a000, 0x1f028930) = 0xffffff9c [0xffd00558, 0]
proot info: vpid 12: pid 28051
proot info: vpid 12: sysenter start: openat(0xffffff9c, 0xf196550, 0xa4800, 0x0, 0x1f028930, 0x404000) = 0xffffff9c [0xffd01248, 0]
proot info: vpid 12: translate("/root/test" + ".")
proot info: vpid 12:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/root/test/."
proot info: vpid 12: sysenter end: openat(0xffffff9c, 0xffd01200, 0xa4800, 0x0, 0x1f028930, 0x404000) = 0xffffff9c [0xffd01248, 0]
proot info: vpid 12: sysenter start: fstat64(0x3, 0xffd011f8, 0xffd011f8, 0xad6ffa00, 0x1f028930, 0x3) = 0x3 [0xffd011ec, 0]
proot info: vpid 12: sysenter end: fstat64(0x3, 0xffd011f8, 0xffd011f8, 0xad6ffa00, 0x1f028930, 0x3) = 0x3 [0xffd011ec, 0]
proot info: vpid 12: sysexit start: fstat64(0x0, 0xffd011f8, 0xffd011f8, 0xad6ffa00, 0x1f028930, 0x3) = 0x0 [0xffd011ec, 0]
proot info: vpid 12: sysexit end: fstat64(0x0, 0xffd011f8, 0xffd011f8, 0xad6ffa00, 0x1f028930, 0x3) = 0x0 [0xffd011ec, 0]
proot info: vpid 12: sysenter start: brk(0xf1ca000, 0x80000000, 0xf1ca000, 0xebe6a000, 0xf1a4000, 0x26000) = 0xf1ca000 [0xffd010bc, 0]
proot info: vpid 12: sysenter end: mremap(0xf0d5000, 0xcf000, 0xf5000, 0x0, 0x0, 0x26000) = 0xf0d5000 [0xffd010bc, 0]
proot info: vpid 12: sysexit start: mremap(0xf0d5000, 0xcf000, 0xf5000, 0x0, 0x0, 0x26000) = 0xf0d5000 [0xffd010bc, 0]
proot info: vpid 12: sysexit end: brk(0xf1ca000, 0x80000000, 0xf1ca000, 0xebe6a000, 0xf1a4000, 0x26000) = 0xf1ca000 [0xffd010bc, 0]
proot info: vpid 12: sysenter start: brk(0xf1c2000, 0x20000, 0xf1c2000, 0xebe6a000, 0xf1ca000, 0xffff8000) = 0xf1c2000 [0xffd011dc, 0]            proot info: vpid 12: sysenter end: mremap(0xf0d5000, 0xf5000, 0xed000, 0x0, 0x0, 0xffff8000) = 0xf0d5000 [0xffd011dc, 0]
proot info: vpid 12: sysexit start: mremap(0xf0d5000, 0xf5000, 0xed000, 0x0, 0x0, 0xffff8000) = 0xf0d5000 [0xffd011dc, 0]
proot info: vpid 12: sysexit end: brk(0xf1c2000, 0x20000, 0xf1c2000, 0xebe6a000, 0xf1ca000, 0xffff8000) = 0xf1c2000 [0xffd011dc, 0]
proot info: vpid 12: sysenter start: stat64(0xf196200, 0xffd01268, 0xffd01268, 0xad6ffa00, 0x1f028930, 0xf196200) = 0xf196200 [0xffd0125c, 0]
proot info: vpid 12: translate("/root/test" + "dir_one")
proot info: vpid 12:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/root/test/dir_one"
proot info: vpid 12: sysenter end: stat64(0xffd0120e, 0xffd01268, 0xffd01268, 0xad6ffa00, 0x1f028930, 0xf196200) = 0xffd0120e [0xffd0120e, 0]
proot info: vpid 12: sysexit start: stat64(0x0, 0xffd01268, 0xffd01268, 0xad6ffa00, 0x1f028930, 0xf196200) = 0x0 [0xffd0120e, 0]
proot info: vpid 12: sysexit end: stat64(0x0, 0xffd01268, 0xffd01268, 0xad6ffa00, 0x1f028930, 0xf196200) = 0x0 [0xffd0125c, 0]
proot info: vpid 12: sysenter start: stat64(0xf196200, 0xffd01268, 0xffd01268, 0xad6ffa00, 0x1f028930, 0xf196200) = 0xf196200 [0xffd0125c, 0]
proot info: vpid 12: translate("/root/test" + "dir_two")
proot info: vpid 12:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/root/test/dir_two"
proot info: vpid 12: sysenter end: stat64(0xffd0120e, 0xffd01268, 0xffd01268, 0xad6ffa00, 0x1f028930, 0xf196200) = 0xffd0120e [0xffd0120e, 0]
proot info: vpid 12: sysexit start: stat64(0x0, 0xffd01268, 0xffd01268, 0xad6ffa00, 0x1f028930, 0xf196200) = 0x0 [0xffd0120e, 0]
proot info: vpid 12: sysexit end: stat64(0x0, 0xffd01268, 0xffd01268, 0xad6ffa00, 0x1f028930, 0xf196200) = 0x0 [0xffd0125c, 0]
proot info: vpid 12: translate("/root/test" + "dir_one")
proot info: vpid 12:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/root/test/dir_one"
proot info: vpid 12: sysenter end: stat64(0xffd0120e, 0xffd01268, 0xffd01268, 0xad6ffa00, 0x1f028930, 0xf196200) = 0xffd0120e [0xffd0120e, 0]
proot info: vpid 12: sysexit start: stat64(0x0, 0xffd01268, 0xffd01268, 0xad6ffa00, 0x1f028930, 0xf196200) = 0x0 [0xffd0120e, 0]
proot info: vpid 12: sysexit end: stat64(0x0, 0xffd01268, 0xffd01268, 0xad6ffa00, 0x1f028930, 0xf196200) = 0x0 [0xffd0125c, 0]
proot info: vpid 12: sysenter start: stat64(0xf196200, 0xffd01268, 0xffd01268, 0xad6ffa00, 0x1f028930, 0xf196200) = 0xf196200 [0xffd0125c, 0]
proot info: vpid 12: translate("/root/test" + "dir_two")
proot info: vpid 12:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/root/test/dir_two"
proot info: vpid 12: sysenter end: stat64(0xffd0120e, 0xffd01268, 0xffd01268, 0xad6ffa00, 0x1f028930, 0xf196200) = 0xffd0120e [0xffd0120e, 0]
proot info: vpid 12: sysexit start: stat64(0x0, 0xffd01268, 0xffd01268, 0xad6ffa00, 0x1f028930, 0xf196200) = 0x0 [0xffd0120e, 0]
proot info: vpid 12: sysexit end: stat64(0x0, 0xffd01268, 0xffd01268, 0xad6ffa00, 0x1f028930, 0xf196200) = 0x0 [0xffd0125c, 0]
proot info: vpid 12: exited with status 0
proot info: vpid 1: sysenter start: wait4(0xffffffff, 0xffd013a4, 0xb, 0x0, 0x78, 0x0) = 0xffffffff [0xffd01350, 0]
proot info: vpid 1: sysenter end: wait4(0xffffffff, 0xffd013a4, 0xb, 0x0, 0x78, 0x0) = 0xffffffff [0xffd01350, 0]
proot info: vpid 1: sysexit start: wait4(0x6d93, 0xffd013a4, 0xb, 0x0, 0x78, 0x0) = 0x6d93 [0xffd01350, 0]
proot info: vpid 1: sysexit end: wait4(0x6d93, 0xffd013a4, 0xb, 0x0, 0x78, 0x0) = 0x6d93 [0xffd01350, 0]
proot info: vpid 1: sysenter start: wait4(0xffffffff, 0xffd013a4, 0xb, 0x0, 0x78, 0x0) = 0xffffffff [0xffd01350, 0]
proot info: vpid 1: sysenter end: wait4(0xffffffff, 0xffd013a4, 0xb, 0x0, 0x78, 0x0) = 0xffffffff [0xffd01350, 0]
proot info: vpid 1: sysexit start: wait4(0xfffffff6, 0xffd013a4, 0xb, 0x0, 0x78, 0x0) = 0xfffffff6 [0xffd01350, 0]
proot info: vpid 1: sysexit end: wait4(0xfffffff6, 0xffd013a4, 0xb, 0x0, 0x78, 0x0) = 0xfffffff6 [0xffd01350, 0]
proot info: vpid 1: sysenter start: ioctl(0xff, 0x5410, 0xffd01474, 0xad6ffa00, 0x1f028930, 0xffd01484) = 0xff [0xffd0146c, 0]
proot info: vpid 1: sysenter end: ioctl(0xff, 0x5410, 0xffd01474, 0xad6ffa00, 0x1f028930, 0xffd01484) = 0xff [0xffd0146c, 0]
proot info: vpid 1: sysenter start: stat64(0xf0b3284, 0xffd01958, 0xffd01958, 0xad6ffa00, 0x1f028930, 0xf0ce658) = 0xf0b3284 [0xffd0194c, 0]
proot info: vpid 1: translate("/" + "/tmp")
proot info: vpid 1:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/tmp"
proot info: vpid 1: sysenter end: stat64(0xffd0190c, 0xffd01958, 0xffd01958, 0xad6ffa00, 0x1f028930, 0xf0ce658) = 0xffd0190c [0xffd0190c, 0]
proot info: vpid 1: sysexit start: stat64(0x0, 0xffd01958, 0xffd01958, 0xad6ffa00, 0x1f028930, 0xf0ce658) = 0x0 [0xffd0190c, 0]
proot info: vpid 1: sysexit end: stat64(0x0, 0xffd01958, 0xffd01958, 0xad6ffa00, 0x1f028930, 0xf0ce658) = 0x0 [0xffd0194c, 0]
proot info: vpid 1: sysenter start: faccessat(0xffffff9c, 0xf0b3284, 0x2, 0x0, 0x200, 0x158) = 0xffffff9c [0xffd018b0, 0]
proot info: vpid 1: translate("/" + "/tmp")
proot info: vpid 1:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/tmp"
proot info: vpid 1: sysenter end: faccessat(0xffffff9c, 0xffd01870, 0x2, 0x0, 0x200, 0x158) = 0xffffff9c [0xffd018b0, 0]
proot info: vpid 1: sysenter start: statfs64(0xf0b3284, 0x58, 0xffd01880, 0xad6ffa00, 0x1f028930, 0xebeae4b0) = 0xf0b3284 [0xffd01874, 0]
proot info: vpid 1: translate("/" + "/tmp")
proot info: vpid 1:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/tmp"
proot info: vpid 1: sysenter end: statfs64(0xffd01834, 0x58, 0xffd01880, 0xad6ffa00, 0x1f028930, 0xebeae4b0) = 0xffd01834 [0xffd01834, 0]
proot info: vpid 1: sysexit start: statfs64(0x0, 0x58, 0xffd01880, 0xad6ffa00, 0x1f028930, 0xebeae4b0) = 0x0 [0xffd01834, 0]
proot info: vpid 1: translate("/" + "/dev/shm")
proot info: vpid 1:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/tmp"
proot info: Updating statfs() result to fake tmpfs /dev/shm
proot warning: ptrace(POKEDATA): I/O error
proot info: Updating statfs() result failed
proot info: vpid 1: sysexit end: statfs64(0x0, 0x58, 0xffd01880, 0xad6ffa00, 0x1f028930, 0xebeae4b0) = 0x0 [0xffd01874, 0]
proot info: vpid 1: sysenter start: openat(0xffffff9c, 0xf1a1b10, 0x200c2, 0x180, 0xebe6a000, 0x1f028930) = 0xffffff9c [0xffd01900, 0]
proot info: vpid 1: translate("/" + "/tmp/sh-thd.Alg4P2")
proot info: vpid 1:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/tmp/sh-thd.Alg4P2"
proot info: vpid 1: sysenter end: openat(0xffffff9c, 0xffd018b2, 0x200c2, 0x180, 0xebe6a000, 0x1f028930) = 0xffffff9c [0xffd01900, 0]
proot info: vpid 1: sysenter start: fchmod(0x3, 0x180, 0xad6ffa00, 0x10, 0xf19df00, 0xf19df00) = 0x3 [0xffd01a04, 0]
proot info: vpid 1: sysenter end: fchmod(0x3, 0x180, 0xad6ffa00, 0x10, 0xf19df00, 0xf19df00) = 0x3 [0xffd01a04, 0]
proot info: vpid 1: sysexit start: fchmod(0x0, 0x180, 0xad6ffa00, 0x10, 0xf19df00, 0xf19df00) = 0x0 [0xffd01a04, 0]
proot info: vpid 1: sysexit end: fchmod(0x0, 0x180, 0xad6ffa00, 0x10, 0xf19df00, 0xf19df00) = 0x0 [0xffd01a04, 0]
proot info: vpid 1: sysenter start: openat(0xffffff9c, 0xf1a1b10, 0x20000, 0x0, 0xebe6a000, 0x1f028930) = 0xffffff9c [0xffd019c8, 0]
proot info: vpid 1: translate("/" + "/tmp/sh-thd.Alg4P2")
proot info: vpid 1:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/tmp/sh-thd.Alg4P2"
proot info: vpid 1: sysenter end: openat(0xffffff9c, 0xffd0197a, 0x20000, 0x0, 0xebe6a000, 0x1f028930) = 0xffffff9c [0xffd019c8, 0]
proot info: vpid 1: sysenter start: unlink(0xf1a1b10, 0xffd0197a, 0x78, 0x0, 0xf1961c8, 0x4) = 0xf1a1b10 [0xffd01a04, 0]
proot info: vpid 1: translate("/" + "/tmp/sh-thd.Alg4P2")
proot info: vpid 1:          -> "/data/data/com.termux/files/home/ubuntu-in-termux/ubuntu-fs/tmp/sh-thd.Alg4P2"
proot info: vpid 1: sysenter end: unlink(0xffd019b6, 0xffd0197a, 0x78, 0x0, 0xf1961c8, 0x4) = 0xffd019b6 [0xffd019b6, 0]
proot info: vpid 1: sysexit start: unlink(0x0, 0xffd0197a, 0x78, 0x0, 0xf1961c8, 0x4) = 0x0 [0xffd019b6, 0]
proot info: vpid 1: sysexit end: unlink(0x0, 0xffd0197a, 0x78, 0x0, 0xf1961c8, 0x4) = 0x0 [0xffd01a04, 0]
proot info: vpid 1: sysenter start: fchmod(0x4, 0x100, 0xad6ffa00, 0xad6ffa00, 0xf1961c8, 0x4) = 0x4 [0xffd01a04, 0]
proot info: vpid 1: sysenter end: fchmod(0x4, 0x100, 0xad6ffa00, 0xad6ffa00, 0xf1961c8, 0x4) = 0x4 [0xffd01a04, 0]
proot info: vpid 1: sysexit start: fchmod(0x0, 0x100, 0xad6ffa00, 0xad6ffa00, 0xf1961c8, 0x4) = 0x0 [0xffd01a04, 0]
proot info: vpid 1: sysexit end: fchmod(0x0, 0x100, 0xad6ffa00, 0xad6ffa00, 0xf1961c8, 0x4) = 0x0 [0xffd01a04, 0]
proot info: vpid 1: sysenter start: ioctl(0x0, 0x5401, 0xffd016c0, 0xffd01700, 0xad6ffa00, 0x158) = 0x0 [0xffd016b8, 0]
proot info: vpid 1: sysenter end: ioctl(0x0, 0x5401, 0xffd016c0, 0xffd01700, 0xad6ffa00, 0x158) = 0x0 [0xffd016b8, 0]
proot info: vpid 1: sysenter start: ioctl(0x0, 0x5401, 0xffd016c0, 0xffd01700, 0xad6ffa00, 0x158) = 0x0 [0xffd016b8, 0]
proot info: vpid 1: sysenter end: ioctl(0x0, 0x5401, 0xffd016c0, 0xffd01700, 0xad6ffa00, 0x158) = 0x0 [0xffd016b8, 0]
proot info: vpid 1: sysenter start: ioctl(0x0, 0x5401, 0xffd016c0, 0xffd01700, 0xad6ffa00, 0x158) = 0x0 [0xffd016b8, 0]
proot info: vpid 1: sysenter end: ioctl(0x0, 0x5401, 0xffd016c0, 0xffd01700, 0xad6ffa00, 0x158) = 0x0 [0xffd016b8, 0]
proot info: vpid 1: sysenter start: openat(0xffffff9c, 0xf196320, 0x20241, 0x1b6, 0xebe6a000, 0x1f028930) = 0xffffff9c [0xffd01a40, 0]
proot info: vpid 1: translate("/" + "/dev/null")
proot info: vpid 1:          -> "/dev/null"
proot info: vpid 1: sysenter end: openat(0xffffff9c, 0xffd01a36, 0x20241, 0x1b6, 0xebe6a000, 0x1f028930) = 0xffffff9c [0xffd01a40, 0]

**Comment by michalbednarski** [comment]
I've pushed fix to `master` branch, you can try it now by building from source, I'll send fix to Termux apt repo in few days.

As upstream proot has no `/dev/shm` is tmpfs emulation, I think this issue won't occur there and proot-me/proot#213 can be closed.

**Comment by ferfebles** [comment]
Built from source and works great!!

Thanks!!!

**Comment by michalbednarski** [comment]
Closing issue as update is now live in Termux apt repository

**Comment by ferfebles** [comment]
Thanks!
