### ISSUE TITLE
flatpak remote-add do not work it want to access system PCI and root access produces other bug

### ISSUE THREAD

**Issue by JanuszChmiel** [termux/proot#97]
Dear Proot specialists,
I have decided to use Arch Linux which have been brought for Android users by excellent Bash script from MR Rausty.
I have even built many apps including Gradio for my device, because ArchLinux AUR repo do not contain so many ARM64 packages.
I have started to build Shortwave.
Unfortunately, I can not use gnome-builder GUI app to install dependencies automatically. It require some process capability which can not be used on Android 8.

I have wanted to run other command to install latest Rust but it is impossible.
When I type as non root user.

flatpak remote-add rust_nightly https://haeckerfelix.de/~repo/rust_nightly.flatpakrepo
Error it is impossible to connect to The system bus.

And when I type The same command as root after typing su
unauthorized memory access (SIGSEGV) 
I Am still dreaming how complex would be to emulate process operations from Proot code, which are disabled by The security restrictions for Android 8.0.
If it would not be possible to inject some source code for Android 7 or 6.0 to avoid complex programming to only emulate some process activityes.
Thank you very much for yours help.
I could build Gradio, even Orca and I can even listen Radio stations for more than 4 hours without sound issues and without system stability problem. I can even run Seamonkey including E-mail client support on Arch Linux.
So I think, that this distribution have The future.

**Comment by Grimler91** [comment]
Closing since this has not been updated in quite a while, please fill in the [bug report template](https://github.com/termux/proot/issues/new?assignees=&labels=&template=bug_report.md) if this is still an issue
