### ISSUE TITLE
cannot link executable "proot": library "libtalloc.so.2" not found 

### ISSUE THREAD

**Issue by whitehattamil** [termux/proot#98]
cannot link executable "proot": library "libtalloc.so.2" not found
Please help me

**Comment by xeffyr** [comment]
What is your `termux-info` output ?

**Comment by whitehattamil** [comment]
![Screenshot_2020-03-01-18-23-33](https://user-images.githubusercontent.com/61619901/75626037-f7231300-5be9-11ea-85f4-9903635ff58a.jpg)

**Comment by whitehattamil** [comment]
![Uploading Screenshot_2020-03-01-18-23-33.jpg…]()

**Comment by whitehattamil** [comment]
> What is your `termux-info` output ?

![Screenshot_2020-03-01-18-23-33](https://user-images.githubusercontent.com/61619901/75626133-c98a9980-5bea-11ea-9ea9-2e485a317f85.jpg)

**Comment by sankethj** [comment]
CANNOT LINK EXECUTABLE "proot": library "libtalloc.so.2" not found

**Comment by sankethj** [comment]
![Screenshot_2020-04-28-09-53-38-204_com termux](https://user-images.githubusercontent.com/60228223/80479213-4c6e6d00-896c-11ea-827b-b658d4cce4d2.jpg)

**Comment by sankethj** [comment]
Help please 🥺

**Comment by michalbednarski** [comment]
Reinstall latest libtalloc and proot from apt:

```
apt update
apt install --reinstall libtalloc proot
```
